-- FIFA World Cup 2026 official draw (48 teams, 104-match schedule)
-- Source: scripts/fifa-wc2026-official-data.mjs
-- Generated by scripts/generate-fifa-official-migration.mjs

INSERT OR IGNORE INTO venues (id, name, city, country, capacity, timezone)
VALUES
  ('v-mexico-city', 'Mexico City Stadium', 'Mexico City', 'Mexico', 87523, 'America/Mexico_City'),
  ('v-guadalajara', 'Estadio Guadalajara', 'Guadalajara', 'Mexico', 49000, 'America/Mexico_City'),
  ('v-monterrey', 'Estadio Monterrey', 'Monterrey', 'Mexico', 53500, 'America/Monterrey'),
  ('v-toronto', 'Toronto Stadium', 'Toronto', 'Canada', 45000, 'America/Toronto'),
  ('v-vancouver', 'BC Place Vancouver', 'Vancouver', 'Canada', 54500, 'America/Vancouver'),
  ('v-los-angeles', 'Los Angeles Stadium', 'Inglewood', 'USA', 70000, 'America/Los_Angeles'),
  ('v-sf-bay', 'San Francisco Bay Area Stadium', 'Santa Clara', 'USA', 68500, 'America/Los_Angeles'),
  ('v-seattle', 'Seattle Stadium', 'Seattle', 'USA', 69000, 'America/Los_Angeles'),
  ('v-dallas', 'Dallas Stadium', 'Arlington', 'USA', 80000, 'America/Chicago'),
  ('v-kansas-city', 'Kansas City Stadium', 'Kansas City', 'USA', 76416, 'America/Chicago'),
  ('v-houston', 'Houston Stadium', 'Houston', 'USA', 72220, 'America/Chicago'),
  ('v-atlanta', 'Atlanta Stadium', 'Atlanta', 'USA', 71000, 'America/New_York'),
  ('v-miami', 'Miami Stadium', 'Miami Gardens', 'USA', 64767, 'America/New_York'),
  ('v-boston', 'Boston Stadium', 'Foxborough', 'USA', 65878, 'America/New_York'),
  ('v-philadelphia', 'Philadelphia Stadium', 'Philadelphia', 'USA', 69796, 'America/New_York'),
  ('v-metlife', 'New York New Jersey Stadium', 'East Rutherford', 'USA', 82500, 'America/New_York');

INSERT OR IGNORE INTO teams (id, name, short_name, country_code, confederation, fifa_ranking, elo_rating, collective_strength_rating)
VALUES
  ('team-w26-a1', 'Mexico', 'MEX', 'MX', 'CONCACAF', 99, 1500, 0.5),
  ('team-w26-a2', 'South Africa', 'RSA', 'ZA', 'CAF', 99, 1500, 0.5),
  ('team-w26-a3', 'Korea Republic', 'KOR', 'KR', 'AFC', 99, 1500, 0.5),
  ('team-w26-a4', 'Czechia', 'CZE', 'CZ', 'UEFA', 99, 1500, 0.5),
  ('team-w26-b1', 'Canada', 'CAN', 'CA', 'CONCACAF', 99, 1500, 0.5),
  ('team-w26-b2', 'Bosnia and Herzegovina', 'BIH', 'BA', 'UEFA', 99, 1500, 0.5),
  ('team-w26-b3', 'Qatar', 'QAT', 'QA', 'AFC', 99, 1500, 0.5),
  ('team-w26-b4', 'Switzerland', 'SUI', 'CH', 'UEFA', 99, 1500, 0.5),
  ('team-w26-c1', 'Haiti', 'HAI', 'HT', 'CONCACAF', 99, 1500, 0.5),
  ('team-w26-c2', 'Scotland', 'SCO', 'GB', 'UEFA', 99, 1500, 0.5),
  ('team-w26-c3', 'Brazil', 'BRA', 'BR', 'CONMEBOL', 99, 1500, 0.5),
  ('team-w26-c4', 'Morocco', 'MAR', 'MA', 'CAF', 99, 1500, 0.5),
  ('team-w26-d1', 'United States', 'USA', 'US', 'CONCACAF', 99, 1500, 0.5),
  ('team-w26-d2', 'Paraguay', 'PAR', 'PY', 'CONMEBOL', 99, 1500, 0.5),
  ('team-w26-d3', 'Australia', 'AUS', 'AU', 'AFC', 99, 1500, 0.5),
  ('team-w26-d4', 'Türkiye', 'TUR', 'TR', 'UEFA', 99, 1500, 0.5),
  ('team-w26-e1', 'Côte d''Ivoire', 'CIV', 'CI', 'CAF', 99, 1500, 0.5),
  ('team-w26-e2', 'Ecuador', 'ECU', 'EC', 'CONMEBOL', 99, 1500, 0.5),
  ('team-w26-e3', 'Germany', 'GER', 'DE', 'UEFA', 99, 1500, 0.5),
  ('team-w26-e4', 'Curaçao', 'CUW', 'CW', 'CONCACAF', 99, 1500, 0.5),
  ('team-w26-f1', 'Netherlands', 'NED', 'NL', 'UEFA', 99, 1500, 0.5),
  ('team-w26-f2', 'Japan', 'JPN', 'JP', 'AFC', 99, 1500, 0.5),
  ('team-w26-f3', 'Sweden', 'SWE', 'SE', 'UEFA', 99, 1500, 0.5),
  ('team-w26-f4', 'Tunisia', 'TUN', 'TN', 'CAF', 99, 1500, 0.5),
  ('team-w26-g1', 'IR Iran', 'IRN', 'IR', 'AFC', 99, 1500, 0.5),
  ('team-w26-g2', 'New Zealand', 'NZL', 'NZ', 'OFC', 99, 1500, 0.5),
  ('team-w26-g3', 'Belgium', 'BEL', 'BE', 'UEFA', 99, 1500, 0.5),
  ('team-w26-g4', 'Egypt', 'EGY', 'EG', 'CAF', 99, 1500, 0.5),
  ('team-w26-h1', 'Saudi Arabia', 'KSA', 'SA', 'AFC', 99, 1500, 0.5),
  ('team-w26-h2', 'Uruguay', 'URU', 'UY', 'CONMEBOL', 99, 1500, 0.5),
  ('team-w26-h3', 'Spain', 'ESP', 'ES', 'UEFA', 99, 1500, 0.5),
  ('team-w26-h4', 'Cabo Verde', 'CPV', 'CV', 'CAF', 99, 1500, 0.5),
  ('team-w26-i1', 'France', 'FRA', 'FR', 'UEFA', 99, 1500, 0.5),
  ('team-w26-i2', 'Senegal', 'SEN', 'SN', 'CAF', 99, 1500, 0.5),
  ('team-w26-i3', 'Iraq', 'IRQ', 'IQ', 'AFC', 99, 1500, 0.5),
  ('team-w26-i4', 'Norway', 'NOR', 'NO', 'UEFA', 99, 1500, 0.5),
  ('team-w26-j1', 'Argentina', 'ARG', 'AR', 'CONMEBOL', 99, 1500, 0.5),
  ('team-w26-j2', 'Algeria', 'ALG', 'DZ', 'CAF', 99, 1500, 0.5),
  ('team-w26-j3', 'Austria', 'AUT', 'AT', 'UEFA', 99, 1500, 0.5),
  ('team-w26-j4', 'Jordan', 'JOR', 'JO', 'AFC', 99, 1500, 0.5),
  ('team-w26-k1', 'Portugal', 'POR', 'PT', 'UEFA', 99, 1500, 0.5),
  ('team-w26-k2', 'Congo DR', 'COD', 'CD', 'CAF', 99, 1500, 0.5),
  ('team-w26-k3', 'Uzbekistan', 'UZB', 'UZ', 'AFC', 99, 1500, 0.5),
  ('team-w26-k4', 'Colombia', 'COL', 'CO', 'CONMEBOL', 99, 1500, 0.5),
  ('team-w26-l1', 'Ghana', 'GHA', 'GH', 'CAF', 99, 1500, 0.5),
  ('team-w26-l2', 'Panama', 'PAN', 'PA', 'CONCACAF', 99, 1500, 0.5),
  ('team-w26-l3', 'England', 'ENG', 'GB', 'UEFA', 99, 1500, 0.5),
  ('team-w26-l4', 'Croatia', 'CRO', 'HR', 'UEFA', 99, 1500, 0.5);

UPDATE teams SET name = 'Mexico', short_name = 'MEX', country_code = 'MX', confederation = 'CONCACAF' WHERE id = 'team-w26-a1';
UPDATE teams SET name = 'South Africa', short_name = 'RSA', country_code = 'ZA', confederation = 'CAF' WHERE id = 'team-w26-a2';
UPDATE teams SET name = 'Korea Republic', short_name = 'KOR', country_code = 'KR', confederation = 'AFC' WHERE id = 'team-w26-a3';
UPDATE teams SET name = 'Czechia', short_name = 'CZE', country_code = 'CZ', confederation = 'UEFA' WHERE id = 'team-w26-a4';
UPDATE teams SET name = 'Canada', short_name = 'CAN', country_code = 'CA', confederation = 'CONCACAF' WHERE id = 'team-w26-b1';
UPDATE teams SET name = 'Bosnia and Herzegovina', short_name = 'BIH', country_code = 'BA', confederation = 'UEFA' WHERE id = 'team-w26-b2';
UPDATE teams SET name = 'Qatar', short_name = 'QAT', country_code = 'QA', confederation = 'AFC' WHERE id = 'team-w26-b3';
UPDATE teams SET name = 'Switzerland', short_name = 'SUI', country_code = 'CH', confederation = 'UEFA' WHERE id = 'team-w26-b4';
UPDATE teams SET name = 'Haiti', short_name = 'HAI', country_code = 'HT', confederation = 'CONCACAF' WHERE id = 'team-w26-c1';
UPDATE teams SET name = 'Scotland', short_name = 'SCO', country_code = 'GB', confederation = 'UEFA' WHERE id = 'team-w26-c2';
UPDATE teams SET name = 'Brazil', short_name = 'BRA', country_code = 'BR', confederation = 'CONMEBOL' WHERE id = 'team-w26-c3';
UPDATE teams SET name = 'Morocco', short_name = 'MAR', country_code = 'MA', confederation = 'CAF' WHERE id = 'team-w26-c4';
UPDATE teams SET name = 'United States', short_name = 'USA', country_code = 'US', confederation = 'CONCACAF' WHERE id = 'team-w26-d1';
UPDATE teams SET name = 'Paraguay', short_name = 'PAR', country_code = 'PY', confederation = 'CONMEBOL' WHERE id = 'team-w26-d2';
UPDATE teams SET name = 'Australia', short_name = 'AUS', country_code = 'AU', confederation = 'AFC' WHERE id = 'team-w26-d3';
UPDATE teams SET name = 'Türkiye', short_name = 'TUR', country_code = 'TR', confederation = 'UEFA' WHERE id = 'team-w26-d4';
UPDATE teams SET name = 'Côte d''Ivoire', short_name = 'CIV', country_code = 'CI', confederation = 'CAF' WHERE id = 'team-w26-e1';
UPDATE teams SET name = 'Ecuador', short_name = 'ECU', country_code = 'EC', confederation = 'CONMEBOL' WHERE id = 'team-w26-e2';
UPDATE teams SET name = 'Germany', short_name = 'GER', country_code = 'DE', confederation = 'UEFA' WHERE id = 'team-w26-e3';
UPDATE teams SET name = 'Curaçao', short_name = 'CUW', country_code = 'CW', confederation = 'CONCACAF' WHERE id = 'team-w26-e4';
UPDATE teams SET name = 'Netherlands', short_name = 'NED', country_code = 'NL', confederation = 'UEFA' WHERE id = 'team-w26-f1';
UPDATE teams SET name = 'Japan', short_name = 'JPN', country_code = 'JP', confederation = 'AFC' WHERE id = 'team-w26-f2';
UPDATE teams SET name = 'Sweden', short_name = 'SWE', country_code = 'SE', confederation = 'UEFA' WHERE id = 'team-w26-f3';
UPDATE teams SET name = 'Tunisia', short_name = 'TUN', country_code = 'TN', confederation = 'CAF' WHERE id = 'team-w26-f4';
UPDATE teams SET name = 'IR Iran', short_name = 'IRN', country_code = 'IR', confederation = 'AFC' WHERE id = 'team-w26-g1';
UPDATE teams SET name = 'New Zealand', short_name = 'NZL', country_code = 'NZ', confederation = 'OFC' WHERE id = 'team-w26-g2';
UPDATE teams SET name = 'Belgium', short_name = 'BEL', country_code = 'BE', confederation = 'UEFA' WHERE id = 'team-w26-g3';
UPDATE teams SET name = 'Egypt', short_name = 'EGY', country_code = 'EG', confederation = 'CAF' WHERE id = 'team-w26-g4';
UPDATE teams SET name = 'Saudi Arabia', short_name = 'KSA', country_code = 'SA', confederation = 'AFC' WHERE id = 'team-w26-h1';
UPDATE teams SET name = 'Uruguay', short_name = 'URU', country_code = 'UY', confederation = 'CONMEBOL' WHERE id = 'team-w26-h2';
UPDATE teams SET name = 'Spain', short_name = 'ESP', country_code = 'ES', confederation = 'UEFA' WHERE id = 'team-w26-h3';
UPDATE teams SET name = 'Cabo Verde', short_name = 'CPV', country_code = 'CV', confederation = 'CAF' WHERE id = 'team-w26-h4';
UPDATE teams SET name = 'France', short_name = 'FRA', country_code = 'FR', confederation = 'UEFA' WHERE id = 'team-w26-i1';
UPDATE teams SET name = 'Senegal', short_name = 'SEN', country_code = 'SN', confederation = 'CAF' WHERE id = 'team-w26-i2';
UPDATE teams SET name = 'Iraq', short_name = 'IRQ', country_code = 'IQ', confederation = 'AFC' WHERE id = 'team-w26-i3';
UPDATE teams SET name = 'Norway', short_name = 'NOR', country_code = 'NO', confederation = 'UEFA' WHERE id = 'team-w26-i4';
UPDATE teams SET name = 'Argentina', short_name = 'ARG', country_code = 'AR', confederation = 'CONMEBOL' WHERE id = 'team-w26-j1';
UPDATE teams SET name = 'Algeria', short_name = 'ALG', country_code = 'DZ', confederation = 'CAF' WHERE id = 'team-w26-j2';
UPDATE teams SET name = 'Austria', short_name = 'AUT', country_code = 'AT', confederation = 'UEFA' WHERE id = 'team-w26-j3';
UPDATE teams SET name = 'Jordan', short_name = 'JOR', country_code = 'JO', confederation = 'AFC' WHERE id = 'team-w26-j4';
UPDATE teams SET name = 'Portugal', short_name = 'POR', country_code = 'PT', confederation = 'UEFA' WHERE id = 'team-w26-k1';
UPDATE teams SET name = 'Congo DR', short_name = 'COD', country_code = 'CD', confederation = 'CAF' WHERE id = 'team-w26-k2';
UPDATE teams SET name = 'Uzbekistan', short_name = 'UZB', country_code = 'UZ', confederation = 'AFC' WHERE id = 'team-w26-k3';
UPDATE teams SET name = 'Colombia', short_name = 'COL', country_code = 'CO', confederation = 'CONMEBOL' WHERE id = 'team-w26-k4';
UPDATE teams SET name = 'Ghana', short_name = 'GHA', country_code = 'GH', confederation = 'CAF' WHERE id = 'team-w26-l1';
UPDATE teams SET name = 'Panama', short_name = 'PAN', country_code = 'PA', confederation = 'CONCACAF' WHERE id = 'team-w26-l2';
UPDATE teams SET name = 'England', short_name = 'ENG', country_code = 'GB', confederation = 'UEFA' WHERE id = 'team-w26-l3';
UPDATE teams SET name = 'Croatia', short_name = 'CRO', country_code = 'HR', confederation = 'UEFA' WHERE id = 'team-w26-l4';

UPDATE teams SET name = 'United States', short_name = 'USA', country_code = 'US', confederation = 'CONCACAF' WHERE id = 'team-usa';
UPDATE teams SET name = 'Mexico', short_name = 'MEX', country_code = 'MX', confederation = 'CONCACAF' WHERE id = 'team-mex';
UPDATE teams SET name = 'Argentina', short_name = 'ARG', country_code = 'AR', confederation = 'CONMEBOL' WHERE id = 'team-arg';
UPDATE teams SET name = 'Brazil', short_name = 'BRA', country_code = 'BR', confederation = 'CONMEBOL' WHERE id = 'team-bra';
UPDATE teams SET name = 'France', short_name = 'FRA', country_code = 'FR', confederation = 'UEFA' WHERE id = 'team-fra';
UPDATE teams SET name = 'England', short_name = 'ENG', country_code = 'GB', confederation = 'UEFA' WHERE id = 'team-eng';

UPDATE matches SET
  home_team_id = 'team-w26-a1',
  away_team_id = 'team-w26-a2',
  kickoff_utc = '2026-06-11T19:00:00Z',
  venue_id = 'v-mexico-city',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-ga-1v2';

UPDATE matches SET
  home_team_id = 'team-w26-a3',
  away_team_id = 'team-w26-a4',
  kickoff_utc = '2026-06-11T17:00:00Z',
  venue_id = 'v-guadalajara',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-ga-3v4';

UPDATE matches SET
  home_team_id = 'team-w26-b1',
  away_team_id = 'team-w26-b2',
  kickoff_utc = '2026-06-12T17:00:00Z',
  venue_id = 'v-toronto',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gb-1v2';

UPDATE matches SET
  home_team_id = 'team-w26-d1',
  away_team_id = 'team-w26-d2',
  kickoff_utc = '2026-06-12T20:00:00Z',
  venue_id = 'v-los-angeles',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gd-1v2';

UPDATE matches SET
  home_team_id = 'team-w26-c1',
  away_team_id = 'team-w26-c2',
  kickoff_utc = '2026-06-13T17:00:00Z',
  venue_id = 'v-boston',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gc-1v2';

UPDATE matches SET
  home_team_id = 'team-w26-d3',
  away_team_id = 'team-w26-d4',
  kickoff_utc = '2026-06-13T20:00:00Z',
  venue_id = 'v-vancouver',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gd-3v4';

UPDATE matches SET
  home_team_id = 'team-w26-c3',
  away_team_id = 'team-w26-c4',
  kickoff_utc = '2026-06-13T23:00:00Z',
  venue_id = 'v-metlife',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gc-3v4';

UPDATE matches SET
  home_team_id = 'team-w26-b3',
  away_team_id = 'team-w26-b4',
  kickoff_utc = '2026-06-13T17:00:00Z',
  venue_id = 'v-sf-bay',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gb-3v4';

UPDATE matches SET
  home_team_id = 'team-w26-e1',
  away_team_id = 'team-w26-e2',
  kickoff_utc = '2026-06-14T17:00:00Z',
  venue_id = 'v-philadelphia',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-ge-1v2';

UPDATE matches SET
  home_team_id = 'team-w26-e3',
  away_team_id = 'team-w26-e4',
  kickoff_utc = '2026-06-14T20:00:00Z',
  venue_id = 'v-houston',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-ge-3v4';

UPDATE matches SET
  home_team_id = 'team-w26-f1',
  away_team_id = 'team-w26-f2',
  kickoff_utc = '2026-06-14T23:00:00Z',
  venue_id = 'v-dallas',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gf-1v2';

UPDATE matches SET
  home_team_id = 'team-w26-f3',
  away_team_id = 'team-w26-f4',
  kickoff_utc = '2026-06-14T17:00:00Z',
  venue_id = 'v-monterrey',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gf-3v4';

UPDATE matches SET
  home_team_id = 'team-w26-h1',
  away_team_id = 'team-w26-h2',
  kickoff_utc = '2026-06-15T17:00:00Z',
  venue_id = 'v-miami',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gh-1v2';

UPDATE matches SET
  home_team_id = 'team-w26-h3',
  away_team_id = 'team-w26-h4',
  kickoff_utc = '2026-06-15T20:00:00Z',
  venue_id = 'v-atlanta',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gh-3v4';

UPDATE matches SET
  home_team_id = 'team-w26-g1',
  away_team_id = 'team-w26-g2',
  kickoff_utc = '2026-06-15T23:00:00Z',
  venue_id = 'v-los-angeles',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gg-1v2';

UPDATE matches SET
  home_team_id = 'team-w26-g3',
  away_team_id = 'team-w26-g4',
  kickoff_utc = '2026-06-15T17:00:00Z',
  venue_id = 'v-seattle',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gg-3v4';

UPDATE matches SET
  home_team_id = 'team-w26-i1',
  away_team_id = 'team-w26-i2',
  kickoff_utc = '2026-06-16T17:00:00Z',
  venue_id = 'v-metlife',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gi-1v2';

UPDATE matches SET
  home_team_id = 'team-w26-i3',
  away_team_id = 'team-w26-i4',
  kickoff_utc = '2026-06-16T20:00:00Z',
  venue_id = 'v-boston',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gi-3v4';

UPDATE matches SET
  home_team_id = 'team-w26-j1',
  away_team_id = 'team-w26-j2',
  kickoff_utc = '2026-06-16T23:00:00Z',
  venue_id = 'v-kansas-city',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gj-1v2';

UPDATE matches SET
  home_team_id = 'team-w26-j3',
  away_team_id = 'team-w26-j4',
  kickoff_utc = '2026-06-16T17:00:00Z',
  venue_id = 'v-sf-bay',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gj-3v4';

UPDATE matches SET
  home_team_id = 'team-w26-l1',
  away_team_id = 'team-w26-l2',
  kickoff_utc = '2026-06-17T17:00:00Z',
  venue_id = 'v-toronto',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gl-1v2';

UPDATE matches SET
  home_team_id = 'team-w26-l3',
  away_team_id = 'team-w26-l4',
  kickoff_utc = '2026-06-17T20:00:00Z',
  venue_id = 'v-dallas',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gl-3v4';

UPDATE matches SET
  home_team_id = 'team-w26-k1',
  away_team_id = 'team-w26-k2',
  kickoff_utc = '2026-06-17T23:00:00Z',
  venue_id = 'v-houston',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gk-1v2';

UPDATE matches SET
  home_team_id = 'team-w26-k3',
  away_team_id = 'team-w26-k4',
  kickoff_utc = '2026-06-17T17:00:00Z',
  venue_id = 'v-mexico-city',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gk-3v4';

UPDATE matches SET
  home_team_id = 'team-w26-a4',
  away_team_id = 'team-w26-a2',
  kickoff_utc = '2026-06-18T17:00:00Z',
  venue_id = 'v-atlanta',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-ga-2v4';

UPDATE matches SET
  home_team_id = 'team-w26-b4',
  away_team_id = 'team-w26-b2',
  kickoff_utc = '2026-06-18T20:00:00Z',
  venue_id = 'v-los-angeles',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gb-2v4';

UPDATE matches SET
  home_team_id = 'team-w26-b1',
  away_team_id = 'team-w26-b3',
  kickoff_utc = '2026-06-18T23:00:00Z',
  venue_id = 'v-vancouver',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gb-1v3';

UPDATE matches SET
  home_team_id = 'team-w26-a1',
  away_team_id = 'team-w26-a3',
  kickoff_utc = '2026-06-18T17:00:00Z',
  venue_id = 'v-guadalajara',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-ga-1v3';

UPDATE matches SET
  home_team_id = 'team-w26-c3',
  away_team_id = 'team-w26-c1',
  kickoff_utc = '2026-06-19T17:00:00Z',
  venue_id = 'v-philadelphia',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gc-1v3';

UPDATE matches SET
  home_team_id = 'team-w26-c2',
  away_team_id = 'team-w26-c4',
  kickoff_utc = '2026-06-19T20:00:00Z',
  venue_id = 'v-boston',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gc-2v4';

UPDATE matches SET
  home_team_id = 'team-w26-d4',
  away_team_id = 'team-w26-d2',
  kickoff_utc = '2026-06-19T23:00:00Z',
  venue_id = 'v-sf-bay',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gd-2v4';

UPDATE matches SET
  home_team_id = 'team-w26-d1',
  away_team_id = 'team-w26-d3',
  kickoff_utc = '2026-06-19T17:00:00Z',
  venue_id = 'v-seattle',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gd-1v3';

UPDATE matches SET
  home_team_id = 'team-w26-e3',
  away_team_id = 'team-w26-e1',
  kickoff_utc = '2026-06-20T17:00:00Z',
  venue_id = 'v-toronto',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-ge-1v3';

UPDATE matches SET
  home_team_id = 'team-w26-e2',
  away_team_id = 'team-w26-e4',
  kickoff_utc = '2026-06-20T20:00:00Z',
  venue_id = 'v-kansas-city',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-ge-2v4';

UPDATE matches SET
  home_team_id = 'team-w26-f1',
  away_team_id = 'team-w26-f3',
  kickoff_utc = '2026-06-20T23:00:00Z',
  venue_id = 'v-houston',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gf-1v3';

UPDATE matches SET
  home_team_id = 'team-w26-f4',
  away_team_id = 'team-w26-f2',
  kickoff_utc = '2026-06-20T17:00:00Z',
  venue_id = 'v-monterrey',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gf-2v4';

UPDATE matches SET
  home_team_id = 'team-w26-h2',
  away_team_id = 'team-w26-h4',
  kickoff_utc = '2026-06-21T17:00:00Z',
  venue_id = 'v-miami',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gh-2v4';

UPDATE matches SET
  home_team_id = 'team-w26-h3',
  away_team_id = 'team-w26-h1',
  kickoff_utc = '2026-06-21T20:00:00Z',
  venue_id = 'v-atlanta',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gh-1v3';

UPDATE matches SET
  home_team_id = 'team-w26-g3',
  away_team_id = 'team-w26-g1',
  kickoff_utc = '2026-06-21T23:00:00Z',
  venue_id = 'v-los-angeles',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gg-1v3';

UPDATE matches SET
  home_team_id = 'team-w26-g2',
  away_team_id = 'team-w26-g4',
  kickoff_utc = '2026-06-21T17:00:00Z',
  venue_id = 'v-vancouver',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gg-2v4';

UPDATE matches SET
  home_team_id = 'team-w26-i4',
  away_team_id = 'team-w26-i2',
  kickoff_utc = '2026-06-22T17:00:00Z',
  venue_id = 'v-metlife',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gi-2v4';

UPDATE matches SET
  home_team_id = 'team-w26-i1',
  away_team_id = 'team-w26-i3',
  kickoff_utc = '2026-06-22T20:00:00Z',
  venue_id = 'v-philadelphia',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gi-1v3';

UPDATE matches SET
  home_team_id = 'team-w26-j1',
  away_team_id = 'team-w26-j3',
  kickoff_utc = '2026-06-22T23:00:00Z',
  venue_id = 'v-dallas',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gj-1v3';

UPDATE matches SET
  home_team_id = 'team-w26-j4',
  away_team_id = 'team-w26-j2',
  kickoff_utc = '2026-06-22T17:00:00Z',
  venue_id = 'v-sf-bay',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gj-2v4';

UPDATE matches SET
  home_team_id = 'team-w26-l3',
  away_team_id = 'team-w26-l1',
  kickoff_utc = '2026-06-23T17:00:00Z',
  venue_id = 'v-boston',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gl-1v3';

UPDATE matches SET
  home_team_id = 'team-w26-l2',
  away_team_id = 'team-w26-l4',
  kickoff_utc = '2026-06-23T20:00:00Z',
  venue_id = 'v-toronto',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gl-2v4';

UPDATE matches SET
  home_team_id = 'team-w26-k1',
  away_team_id = 'team-w26-k3',
  kickoff_utc = '2026-06-23T23:00:00Z',
  venue_id = 'v-houston',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gk-1v3';

UPDATE matches SET
  home_team_id = 'team-w26-k4',
  away_team_id = 'team-w26-k2',
  kickoff_utc = '2026-06-23T17:00:00Z',
  venue_id = 'v-guadalajara',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gk-2v4';

UPDATE matches SET
  home_team_id = 'team-w26-c2',
  away_team_id = 'team-w26-c3',
  kickoff_utc = '2026-06-24T17:00:00Z',
  venue_id = 'v-miami',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gc-2v3';

UPDATE matches SET
  home_team_id = 'team-w26-c4',
  away_team_id = 'team-w26-c1',
  kickoff_utc = '2026-06-24T20:00:00Z',
  venue_id = 'v-atlanta',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gc-1v4';

UPDATE matches SET
  home_team_id = 'team-w26-b4',
  away_team_id = 'team-w26-b1',
  kickoff_utc = '2026-06-24T23:00:00Z',
  venue_id = 'v-vancouver',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gb-1v4';

UPDATE matches SET
  home_team_id = 'team-w26-b2',
  away_team_id = 'team-w26-b3',
  kickoff_utc = '2026-06-24T17:00:00Z',
  venue_id = 'v-seattle',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gb-2v3';

UPDATE matches SET
  home_team_id = 'team-w26-a4',
  away_team_id = 'team-w26-a1',
  kickoff_utc = '2026-06-24T20:00:00Z',
  venue_id = 'v-mexico-city',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-ga-1v4';

UPDATE matches SET
  home_team_id = 'team-w26-a2',
  away_team_id = 'team-w26-a3',
  kickoff_utc = '2026-06-24T23:00:00Z',
  venue_id = 'v-monterrey',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-ga-2v3';

UPDATE matches SET
  home_team_id = 'team-w26-e4',
  away_team_id = 'team-w26-e1',
  kickoff_utc = '2026-06-25T17:00:00Z',
  venue_id = 'v-philadelphia',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-ge-1v4';

UPDATE matches SET
  home_team_id = 'team-w26-e2',
  away_team_id = 'team-w26-e3',
  kickoff_utc = '2026-06-25T20:00:00Z',
  venue_id = 'v-metlife',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-ge-2v3';

UPDATE matches SET
  home_team_id = 'team-w26-f2',
  away_team_id = 'team-w26-f3',
  kickoff_utc = '2026-06-25T23:00:00Z',
  venue_id = 'v-dallas',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gf-2v3';

UPDATE matches SET
  home_team_id = 'team-w26-f4',
  away_team_id = 'team-w26-f1',
  kickoff_utc = '2026-06-25T17:00:00Z',
  venue_id = 'v-kansas-city',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gf-1v4';

UPDATE matches SET
  home_team_id = 'team-w26-d4',
  away_team_id = 'team-w26-d1',
  kickoff_utc = '2026-06-25T20:00:00Z',
  venue_id = 'v-los-angeles',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gd-1v4';

UPDATE matches SET
  home_team_id = 'team-w26-d2',
  away_team_id = 'team-w26-d3',
  kickoff_utc = '2026-06-25T23:00:00Z',
  venue_id = 'v-sf-bay',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gd-2v3';

UPDATE matches SET
  home_team_id = 'team-w26-i4',
  away_team_id = 'team-w26-i1',
  kickoff_utc = '2026-06-26T17:00:00Z',
  venue_id = 'v-boston',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gi-1v4';

UPDATE matches SET
  home_team_id = 'team-w26-i2',
  away_team_id = 'team-w26-i3',
  kickoff_utc = '2026-06-26T20:00:00Z',
  venue_id = 'v-toronto',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gi-2v3';

UPDATE matches SET
  home_team_id = 'team-w26-g4',
  away_team_id = 'team-w26-g1',
  kickoff_utc = '2026-06-26T23:00:00Z',
  venue_id = 'v-seattle',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gg-1v4';

UPDATE matches SET
  home_team_id = 'team-w26-g2',
  away_team_id = 'team-w26-g3',
  kickoff_utc = '2026-06-26T17:00:00Z',
  venue_id = 'v-vancouver',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gg-2v3';

UPDATE matches SET
  home_team_id = 'team-w26-h4',
  away_team_id = 'team-w26-h1',
  kickoff_utc = '2026-06-26T20:00:00Z',
  venue_id = 'v-houston',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gh-1v4';

UPDATE matches SET
  home_team_id = 'team-w26-h2',
  away_team_id = 'team-w26-h3',
  kickoff_utc = '2026-06-26T23:00:00Z',
  venue_id = 'v-guadalajara',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gh-2v3';

UPDATE matches SET
  home_team_id = 'team-w26-l2',
  away_team_id = 'team-w26-l3',
  kickoff_utc = '2026-06-27T17:00:00Z',
  venue_id = 'v-metlife',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gl-2v3';

UPDATE matches SET
  home_team_id = 'team-w26-l4',
  away_team_id = 'team-w26-l1',
  kickoff_utc = '2026-06-27T20:00:00Z',
  venue_id = 'v-philadelphia',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gl-1v4';

UPDATE matches SET
  home_team_id = 'team-w26-j2',
  away_team_id = 'team-w26-j3',
  kickoff_utc = '2026-06-27T23:00:00Z',
  venue_id = 'v-kansas-city',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gj-2v3';

UPDATE matches SET
  home_team_id = 'team-w26-j4',
  away_team_id = 'team-w26-j1',
  kickoff_utc = '2026-06-27T17:00:00Z',
  venue_id = 'v-dallas',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gj-1v4';

UPDATE matches SET
  home_team_id = 'team-w26-k4',
  away_team_id = 'team-w26-k1',
  kickoff_utc = '2026-06-27T20:00:00Z',
  venue_id = 'v-miami',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gk-1v4';

UPDATE matches SET
  home_team_id = 'team-w26-k2',
  away_team_id = 'team-w26-k3',
  kickoff_utc = '2026-06-27T23:00:00Z',
  venue_id = 'v-atlanta',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-gk-2v3';

UPDATE matches SET
  kickoff_utc = '2026-06-28T17:00:00Z',
  venue_id = 'v-los-angeles',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r32-01';

UPDATE matches SET
  kickoff_utc = '2026-06-29T17:00:00Z',
  venue_id = 'v-boston',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r32-02';

UPDATE matches SET
  kickoff_utc = '2026-06-29T20:00:00Z',
  venue_id = 'v-monterrey',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r32-03';

UPDATE matches SET
  kickoff_utc = '2026-06-29T23:00:00Z',
  venue_id = 'v-houston',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r32-04';

UPDATE matches SET
  kickoff_utc = '2026-06-30T17:00:00Z',
  venue_id = 'v-metlife',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r32-05';

UPDATE matches SET
  kickoff_utc = '2026-06-30T20:00:00Z',
  venue_id = 'v-dallas',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r32-06';

UPDATE matches SET
  kickoff_utc = '2026-06-30T23:00:00Z',
  venue_id = 'v-mexico-city',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r32-07';

UPDATE matches SET
  kickoff_utc = '2026-07-01T17:00:00Z',
  venue_id = 'v-atlanta',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r32-08';

UPDATE matches SET
  kickoff_utc = '2026-07-01T20:00:00Z',
  venue_id = 'v-sf-bay',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r32-09';

UPDATE matches SET
  kickoff_utc = '2026-07-01T23:00:00Z',
  venue_id = 'v-seattle',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r32-10';

UPDATE matches SET
  kickoff_utc = '2026-07-02T17:00:00Z',
  venue_id = 'v-toronto',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r32-11';

UPDATE matches SET
  kickoff_utc = '2026-07-02T20:00:00Z',
  venue_id = 'v-los-angeles',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r32-12';

UPDATE matches SET
  kickoff_utc = '2026-07-02T23:00:00Z',
  venue_id = 'v-vancouver',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r32-13';

UPDATE matches SET
  kickoff_utc = '2026-07-03T17:00:00Z',
  venue_id = 'v-miami',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r32-14';

UPDATE matches SET
  kickoff_utc = '2026-07-03T20:00:00Z',
  venue_id = 'v-kansas-city',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r32-15';

UPDATE matches SET
  kickoff_utc = '2026-07-03T23:00:00Z',
  venue_id = 'v-dallas',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r32-16';

UPDATE matches SET
  kickoff_utc = '2026-07-04T17:00:00Z',
  venue_id = 'v-philadelphia',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r16-01';

UPDATE matches SET
  kickoff_utc = '2026-07-04T20:00:00Z',
  venue_id = 'v-houston',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r16-02';

UPDATE matches SET
  kickoff_utc = '2026-07-05T17:00:00Z',
  venue_id = 'v-metlife',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r16-03';

UPDATE matches SET
  kickoff_utc = '2026-07-05T20:00:00Z',
  venue_id = 'v-mexico-city',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r16-04';

UPDATE matches SET
  kickoff_utc = '2026-07-06T17:00:00Z',
  venue_id = 'v-dallas',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r16-05';

UPDATE matches SET
  kickoff_utc = '2026-07-06T20:00:00Z',
  venue_id = 'v-seattle',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r16-06';

UPDATE matches SET
  kickoff_utc = '2026-07-07T17:00:00Z',
  venue_id = 'v-atlanta',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r16-07';

UPDATE matches SET
  kickoff_utc = '2026-07-07T20:00:00Z',
  venue_id = 'v-vancouver',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-r16-08';

UPDATE matches SET
  kickoff_utc = '2026-07-09T17:00:00Z',
  venue_id = 'v-boston',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-qf-01';

UPDATE matches SET
  kickoff_utc = '2026-07-10T17:00:00Z',
  venue_id = 'v-los-angeles',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-qf-02';

UPDATE matches SET
  kickoff_utc = '2026-07-11T17:00:00Z',
  venue_id = 'v-miami',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-qf-03';

UPDATE matches SET
  kickoff_utc = '2026-07-11T20:00:00Z',
  venue_id = 'v-kansas-city',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-qf-04';

UPDATE matches SET
  kickoff_utc = '2026-07-14T17:00:00Z',
  venue_id = 'v-dallas',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-sf-01';

UPDATE matches SET
  kickoff_utc = '2026-07-15T17:00:00Z',
  venue_id = 'v-atlanta',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-sf-02';

UPDATE matches SET
  kickoff_utc = '2026-07-18T17:00:00Z',
  venue_id = 'v-miami',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-3rd-01';

UPDATE matches SET
  kickoff_utc = '2026-07-19T17:00:00Z',
  venue_id = 'v-metlife',
  status = 'scheduled',
  home_score = 0,
  away_score = 0
WHERE id = 'm-w26-final-01';

DELETE FROM probability_snapshots WHERE match_id IN (SELECT id FROM matches WHERE tournament_id = 't-2026');
