-- WC 2026 kickoff times aligned to Vietnam schedule (GMT+7)
-- Source: https://thethao247.vn/world-cup/426-lich-thi-dau-world-cup-2026-d399919.html
-- Generated by scripts/generate-vn-kickoff-migration.mjs

UPDATE matches SET kickoff_utc = '2026-06-11T19:00:00Z' WHERE id = 'm-w26-ga-1v2';

UPDATE matches SET kickoff_utc = '2026-06-12T02:00:00Z' WHERE id = 'm-w26-ga-3v4';

UPDATE matches SET kickoff_utc = '2026-06-12T19:00:00Z' WHERE id = 'm-w26-gb-1v2';

UPDATE matches SET kickoff_utc = '2026-06-13T01:00:00Z' WHERE id = 'm-w26-gd-1v2';

UPDATE matches SET kickoff_utc = '2026-06-13T19:00:00Z' WHERE id = 'm-w26-gc-1v2';

UPDATE matches SET kickoff_utc = '2026-06-13T22:00:00Z' WHERE id = 'm-w26-gd-3v4';

UPDATE matches SET kickoff_utc = '2026-06-14T01:00:00Z' WHERE id = 'm-w26-gc-3v4';

UPDATE matches SET kickoff_utc = '2026-06-14T04:00:00Z' WHERE id = 'm-w26-gb-3v4';

UPDATE matches SET kickoff_utc = '2026-06-14T17:00:00Z' WHERE id = 'm-w26-ge-1v2';

UPDATE matches SET kickoff_utc = '2026-06-14T20:00:00Z' WHERE id = 'm-w26-ge-3v4';

UPDATE matches SET kickoff_utc = '2026-06-14T23:00:00Z' WHERE id = 'm-w26-gf-1v2';

UPDATE matches SET kickoff_utc = '2026-06-15T02:00:00Z' WHERE id = 'm-w26-gf-3v4';

UPDATE matches SET kickoff_utc = '2026-06-15T16:00:00Z' WHERE id = 'm-w26-gh-1v2';

UPDATE matches SET kickoff_utc = '2026-06-15T19:00:00Z' WHERE id = 'm-w26-gh-3v4';

UPDATE matches SET kickoff_utc = '2026-06-15T22:00:00Z' WHERE id = 'm-w26-gg-1v2';

UPDATE matches SET kickoff_utc = '2026-06-16T01:00:00Z' WHERE id = 'm-w26-gg-3v4';

UPDATE matches SET kickoff_utc = '2026-06-16T19:00:00Z' WHERE id = 'm-w26-gi-1v2';

UPDATE matches SET kickoff_utc = '2026-06-16T22:00:00Z' WHERE id = 'm-w26-gi-3v4';

UPDATE matches SET kickoff_utc = '2026-06-17T01:00:00Z' WHERE id = 'm-w26-gj-1v2';

UPDATE matches SET kickoff_utc = '2026-06-17T04:00:00Z' WHERE id = 'm-w26-gj-3v4';

UPDATE matches SET kickoff_utc = '2026-06-17T17:00:00Z' WHERE id = 'm-w26-gl-1v2';

UPDATE matches SET kickoff_utc = '2026-06-17T20:00:00Z' WHERE id = 'm-w26-gl-3v4';

UPDATE matches SET kickoff_utc = '2026-06-17T23:00:00Z' WHERE id = 'm-w26-gk-1v2';

UPDATE matches SET kickoff_utc = '2026-06-18T02:00:00Z' WHERE id = 'm-w26-gk-3v4';

UPDATE matches SET kickoff_utc = '2026-06-18T17:00:00Z' WHERE id = 'm-w26-ga-2v4';

UPDATE matches SET kickoff_utc = '2026-06-18T20:00:00Z' WHERE id = 'm-w26-gb-2v4';

UPDATE matches SET kickoff_utc = '2026-06-18T23:00:00Z' WHERE id = 'm-w26-gb-1v3';

UPDATE matches SET kickoff_utc = '2026-06-19T01:00:00Z' WHERE id = 'm-w26-ga-1v3';

UPDATE matches SET kickoff_utc = '2026-06-19T19:00:00Z' WHERE id = 'm-w26-gc-1v3';

UPDATE matches SET kickoff_utc = '2026-06-19T22:00:00Z' WHERE id = 'm-w26-gc-2v4';

UPDATE matches SET kickoff_utc = '2026-06-20T01:00:00Z' WHERE id = 'm-w26-gd-2v4';

UPDATE matches SET kickoff_utc = '2026-06-20T04:00:00Z' WHERE id = 'm-w26-gd-1v3';

UPDATE matches SET kickoff_utc = '2026-06-20T17:00:00Z' WHERE id = 'm-w26-ge-1v3';

UPDATE matches SET kickoff_utc = '2026-06-20T20:00:00Z' WHERE id = 'm-w26-ge-2v4';

UPDATE matches SET kickoff_utc = '2026-06-21T00:00:00Z' WHERE id = 'm-w26-gf-1v3';

UPDATE matches SET kickoff_utc = '2026-06-21T04:00:00Z' WHERE id = 'm-w26-gf-2v4';

UPDATE matches SET kickoff_utc = '2026-06-21T19:00:00Z' WHERE id = 'm-w26-gh-2v4';

UPDATE matches SET kickoff_utc = '2026-06-21T22:00:00Z' WHERE id = 'm-w26-gh-1v3';

UPDATE matches SET kickoff_utc = '2026-06-22T01:00:00Z' WHERE id = 'm-w26-gg-1v3';

UPDATE matches SET kickoff_utc = '2026-06-22T16:00:00Z' WHERE id = 'm-w26-gg-2v4';

UPDATE matches SET kickoff_utc = '2026-06-22T17:00:00Z' WHERE id = 'm-w26-gi-2v4';

UPDATE matches SET kickoff_utc = '2026-06-22T21:00:00Z' WHERE id = 'm-w26-gi-1v3';

UPDATE matches SET kickoff_utc = '2026-06-23T00:00:00Z' WHERE id = 'm-w26-gj-1v3';

UPDATE matches SET kickoff_utc = '2026-06-23T03:00:00Z' WHERE id = 'm-w26-gj-2v4';

UPDATE matches SET kickoff_utc = '2026-06-23T17:00:00Z' WHERE id = 'm-w26-gl-1v3';

UPDATE matches SET kickoff_utc = '2026-06-23T20:00:00Z' WHERE id = 'm-w26-gl-2v4';

UPDATE matches SET kickoff_utc = '2026-06-23T23:00:00Z' WHERE id = 'm-w26-gk-1v3';

UPDATE matches SET kickoff_utc = '2026-06-24T02:00:00Z' WHERE id = 'm-w26-gk-2v4';

UPDATE matches SET kickoff_utc = '2026-06-24T19:00:00Z' WHERE id = 'm-w26-gc-2v3';

UPDATE matches SET kickoff_utc = '2026-06-24T19:00:00Z' WHERE id = 'm-w26-gc-1v4';

UPDATE matches SET kickoff_utc = '2026-06-24T22:00:00Z' WHERE id = 'm-w26-gb-1v4';

UPDATE matches SET kickoff_utc = '2026-06-24T22:00:00Z' WHERE id = 'm-w26-gb-2v3';

UPDATE matches SET kickoff_utc = '2026-06-25T01:00:00Z' WHERE id = 'm-w26-ga-1v4';

UPDATE matches SET kickoff_utc = '2026-06-25T01:00:00Z' WHERE id = 'm-w26-ga-2v3';

UPDATE matches SET kickoff_utc = '2026-06-25T20:00:00Z' WHERE id = 'm-w26-ge-1v4';

UPDATE matches SET kickoff_utc = '2026-06-25T20:00:00Z' WHERE id = 'm-w26-ge-2v3';

UPDATE matches SET kickoff_utc = '2026-06-25T23:00:00Z' WHERE id = 'm-w26-gf-2v3';

UPDATE matches SET kickoff_utc = '2026-06-25T23:00:00Z' WHERE id = 'm-w26-gf-1v4';

UPDATE matches SET kickoff_utc = '2026-06-26T01:00:00Z' WHERE id = 'm-w26-gd-1v4';

UPDATE matches SET kickoff_utc = '2026-06-26T01:00:00Z' WHERE id = 'm-w26-gd-2v3';

UPDATE matches SET kickoff_utc = '2026-06-26T19:00:00Z' WHERE id = 'm-w26-gi-1v4';

UPDATE matches SET kickoff_utc = '2026-06-26T19:00:00Z' WHERE id = 'm-w26-gi-2v3';

UPDATE matches SET kickoff_utc = '2026-06-27T00:00:00Z' WHERE id = 'm-w26-gg-1v4';

UPDATE matches SET kickoff_utc = '2026-06-27T00:00:00Z' WHERE id = 'm-w26-gg-2v3';

UPDATE matches SET kickoff_utc = '2026-06-27T03:00:00Z' WHERE id = 'm-w26-gh-1v4';

UPDATE matches SET kickoff_utc = '2026-06-27T03:00:00Z' WHERE id = 'm-w26-gh-2v3';

UPDATE matches SET kickoff_utc = '2026-06-27T21:00:00Z' WHERE id = 'm-w26-gl-2v3';

UPDATE matches SET kickoff_utc = '2026-06-27T21:00:00Z' WHERE id = 'm-w26-gl-1v4';

UPDATE matches SET kickoff_utc = '2026-06-27T23:30:00Z' WHERE id = 'm-w26-gj-2v3';

UPDATE matches SET kickoff_utc = '2026-06-27T23:30:00Z' WHERE id = 'm-w26-gj-1v4';

UPDATE matches SET kickoff_utc = '2026-06-28T02:00:00Z' WHERE id = 'm-w26-gk-1v4';

UPDATE matches SET kickoff_utc = '2026-06-28T02:00:00Z' WHERE id = 'm-w26-gk-2v3';

UPDATE matches SET kickoff_utc = '2026-06-28T19:00:00Z' WHERE id = 'm-w26-r32-01';

UPDATE matches SET kickoff_utc = '2026-06-29T17:00:00Z' WHERE id = 'm-w26-r32-02';

UPDATE matches SET kickoff_utc = '2026-06-29T20:30:00Z' WHERE id = 'm-w26-r32-03';

UPDATE matches SET kickoff_utc = '2026-06-30T01:00:00Z' WHERE id = 'm-w26-r32-04';

UPDATE matches SET kickoff_utc = '2026-06-30T17:00:00Z' WHERE id = 'm-w26-r32-05';

UPDATE matches SET kickoff_utc = '2026-06-30T21:00:00Z' WHERE id = 'm-w26-r32-06';

UPDATE matches SET kickoff_utc = '2026-07-01T01:00:00Z' WHERE id = 'm-w26-r32-07';

UPDATE matches SET kickoff_utc = '2026-07-01T20:00:00Z' WHERE id = 'm-w26-r32-08';

UPDATE matches SET kickoff_utc = '2026-07-02T00:00:00Z' WHERE id = 'm-w26-r32-09';

UPDATE matches SET kickoff_utc = '2026-07-02T16:00:00Z' WHERE id = 'm-w26-r32-10';

UPDATE matches SET kickoff_utc = '2026-07-02T19:00:00Z' WHERE id = 'm-w26-r32-11';

UPDATE matches SET kickoff_utc = '2026-07-02T23:00:00Z' WHERE id = 'm-w26-r32-12';

UPDATE matches SET kickoff_utc = '2026-07-03T03:00:00Z' WHERE id = 'm-w26-r32-13';

UPDATE matches SET kickoff_utc = '2026-07-03T18:00:00Z' WHERE id = 'm-w26-r32-14';

UPDATE matches SET kickoff_utc = '2026-07-03T22:00:00Z' WHERE id = 'm-w26-r32-15';

UPDATE matches SET kickoff_utc = '2026-07-04T01:30:00Z' WHERE id = 'm-w26-r32-16';

UPDATE matches SET kickoff_utc = '2026-07-04T17:00:00Z' WHERE id = 'm-w26-r16-01';

UPDATE matches SET kickoff_utc = '2026-07-04T21:00:00Z' WHERE id = 'm-w26-r16-02';

UPDATE matches SET kickoff_utc = '2026-07-05T20:00:00Z' WHERE id = 'm-w26-r16-03';

UPDATE matches SET kickoff_utc = '2026-07-06T00:00:00Z' WHERE id = 'm-w26-r16-04';

UPDATE matches SET kickoff_utc = '2026-07-06T19:00:00Z' WHERE id = 'm-w26-r16-05';

UPDATE matches SET kickoff_utc = '2026-07-07T00:00:00Z' WHERE id = 'm-w26-r16-06';

UPDATE matches SET kickoff_utc = '2026-07-07T16:00:00Z' WHERE id = 'm-w26-r16-07';

UPDATE matches SET kickoff_utc = '2026-07-07T20:00:00Z' WHERE id = 'm-w26-r16-08';

UPDATE matches SET kickoff_utc = '2026-07-09T20:00:00Z' WHERE id = 'm-w26-qf-01';

UPDATE matches SET kickoff_utc = '2026-07-10T19:00:00Z' WHERE id = 'm-w26-qf-02';

UPDATE matches SET kickoff_utc = '2026-07-11T21:00:00Z' WHERE id = 'm-w26-qf-03';

UPDATE matches SET kickoff_utc = '2026-07-12T01:00:00Z' WHERE id = 'm-w26-qf-04';

UPDATE matches SET kickoff_utc = '2026-07-14T19:00:00Z' WHERE id = 'm-w26-sf-01';

UPDATE matches SET kickoff_utc = '2026-07-15T19:00:00Z' WHERE id = 'm-w26-sf-02';

UPDATE matches SET kickoff_utc = '2026-07-18T21:00:00Z' WHERE id = 'm-w26-3rd-01';

UPDATE matches SET kickoff_utc = '2026-07-19T19:00:00Z' WHERE id = 'm-w26-final-01';
