-- WC 2026 kickoff times aligned to FIFA Match Centre (UTC)
-- Source: https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/scores-fixtures
-- Generated by scripts/generate-fifa-kickoff-migration.mjs

UPDATE matches SET kickoff_utc = '2026-06-11T19:00:00Z' WHERE id = 'm-w26-ga-1v2';

UPDATE matches SET kickoff_utc = '2026-06-12T02:00:00Z' WHERE id = 'm-w26-ga-3v4';

UPDATE matches SET kickoff_utc = '2026-06-12T19:00:00Z' WHERE id = 'm-w26-gb-1v2';

UPDATE matches SET kickoff_utc = '2026-06-13T01:00:00Z' WHERE id = 'm-w26-gd-1v2';

UPDATE matches SET kickoff_utc = '2026-06-14T01:00:00Z' WHERE id = 'm-w26-gc-1v2';

UPDATE matches SET kickoff_utc = '2026-06-14T04:00:00Z' WHERE id = 'm-w26-gd-3v4';

UPDATE matches SET kickoff_utc = '2026-06-13T22:00:00Z' WHERE id = 'm-w26-gc-3v4';

UPDATE matches SET kickoff_utc = '2026-06-13T19:00:00Z' WHERE id = 'm-w26-gb-3v4';

UPDATE matches SET kickoff_utc = '2026-06-14T23:00:00Z' WHERE id = 'm-w26-ge-1v2';

UPDATE matches SET kickoff_utc = '2026-06-14T17:00:00Z' WHERE id = 'm-w26-ge-3v4';

UPDATE matches SET kickoff_utc = '2026-06-14T20:00:00Z' WHERE id = 'm-w26-gf-1v2';

UPDATE matches SET kickoff_utc = '2026-06-15T02:00:00Z' WHERE id = 'm-w26-gf-3v4';

UPDATE matches SET kickoff_utc = '2026-06-15T22:00:00Z' WHERE id = 'm-w26-gh-1v2';

UPDATE matches SET kickoff_utc = '2026-06-15T16:00:00Z' WHERE id = 'm-w26-gh-3v4';

UPDATE matches SET kickoff_utc = '2026-06-16T01:00:00Z' WHERE id = 'm-w26-gg-1v2';

UPDATE matches SET kickoff_utc = '2026-06-15T19:00:00Z' WHERE id = 'm-w26-gg-3v4';

UPDATE matches SET kickoff_utc = '2026-06-16T19:00:00Z' WHERE id = 'm-w26-gi-1v2';

UPDATE matches SET kickoff_utc = '2026-06-16T22:00:00Z' WHERE id = 'm-w26-gi-3v4';

UPDATE matches SET kickoff_utc = '2026-06-17T01:00:00Z' WHERE id = 'm-w26-gj-1v2';

UPDATE matches SET kickoff_utc = '2026-06-17T04:00:00Z' WHERE id = 'm-w26-gj-3v4';

UPDATE matches SET kickoff_utc = '2026-06-17T23:00:00Z' WHERE id = 'm-w26-gl-1v2';

UPDATE matches SET kickoff_utc = '2026-06-17T20:00:00Z' WHERE id = 'm-w26-gl-3v4';

UPDATE matches SET kickoff_utc = '2026-06-17T17:00:00Z' WHERE id = 'm-w26-gk-1v2';

UPDATE matches SET kickoff_utc = '2026-06-18T02:00:00Z' WHERE id = 'm-w26-gk-3v4';

UPDATE matches SET kickoff_utc = '2026-06-18T16:00:00Z' WHERE id = 'm-w26-ga-2v4';

UPDATE matches SET kickoff_utc = '2026-06-18T19:00:00Z' WHERE id = 'm-w26-gb-2v4';

UPDATE matches SET kickoff_utc = '2026-06-18T22:00:00Z' WHERE id = 'm-w26-gb-1v3';

UPDATE matches SET kickoff_utc = '2026-06-19T01:00:00Z' WHERE id = 'm-w26-ga-1v3';

UPDATE matches SET kickoff_utc = '2026-06-20T00:30:00Z' WHERE id = 'm-w26-gc-1v3';

UPDATE matches SET kickoff_utc = '2026-06-19T22:00:00Z' WHERE id = 'm-w26-gc-2v4';

UPDATE matches SET kickoff_utc = '2026-06-20T03:00:00Z' WHERE id = 'm-w26-gd-2v4';

UPDATE matches SET kickoff_utc = '2026-06-19T19:00:00Z' WHERE id = 'm-w26-gd-1v3';

UPDATE matches SET kickoff_utc = '2026-06-20T20:00:00Z' WHERE id = 'm-w26-ge-1v3';

UPDATE matches SET kickoff_utc = '2026-06-21T00:00:00Z' WHERE id = 'm-w26-ge-2v4';

UPDATE matches SET kickoff_utc = '2026-06-20T17:00:00Z' WHERE id = 'm-w26-gf-1v3';

UPDATE matches SET kickoff_utc = '2026-06-21T04:00:00Z' WHERE id = 'm-w26-gf-2v4';

UPDATE matches SET kickoff_utc = '2026-06-21T22:00:00Z' WHERE id = 'm-w26-gh-2v4';

UPDATE matches SET kickoff_utc = '2026-06-21T16:00:00Z' WHERE id = 'm-w26-gh-1v3';

UPDATE matches SET kickoff_utc = '2026-06-21T19:00:00Z' WHERE id = 'm-w26-gg-1v3';

UPDATE matches SET kickoff_utc = '2026-06-22T01:00:00Z' WHERE id = 'm-w26-gg-2v4';

UPDATE matches SET kickoff_utc = '2026-06-23T00:00:00Z' WHERE id = 'm-w26-gi-2v4';

UPDATE matches SET kickoff_utc = '2026-06-22T21:00:00Z' WHERE id = 'm-w26-gi-1v3';

UPDATE matches SET kickoff_utc = '2026-06-22T17:00:00Z' WHERE id = 'm-w26-gj-1v3';

UPDATE matches SET kickoff_utc = '2026-06-23T03:00:00Z' WHERE id = 'm-w26-gj-2v4';

UPDATE matches SET kickoff_utc = '2026-06-23T20:00:00Z' WHERE id = 'm-w26-gl-1v3';

UPDATE matches SET kickoff_utc = '2026-06-23T23:00:00Z' WHERE id = 'm-w26-gl-2v4';

UPDATE matches SET kickoff_utc = '2026-06-23T17:00:00Z' WHERE id = 'm-w26-gk-1v3';

UPDATE matches SET kickoff_utc = '2026-06-24T02:00:00Z' WHERE id = 'm-w26-gk-2v4';

UPDATE matches SET kickoff_utc = '2026-06-24T22:00:00Z' WHERE id = 'm-w26-gc-2v3';

UPDATE matches SET kickoff_utc = '2026-06-24T22:00:00Z' WHERE id = 'm-w26-gc-1v4';

UPDATE matches SET kickoff_utc = '2026-06-24T19:00:00Z' WHERE id = 'm-w26-gb-1v4';

UPDATE matches SET kickoff_utc = '2026-06-24T19:00:00Z' WHERE id = 'm-w26-gb-2v3';

UPDATE matches SET kickoff_utc = '2026-06-25T01:00:00Z' WHERE id = 'm-w26-ga-1v4';

UPDATE matches SET kickoff_utc = '2026-06-25T01:00:00Z' WHERE id = 'm-w26-ga-2v3';

UPDATE matches SET kickoff_utc = '2026-06-25T20:00:00Z' WHERE id = 'm-w26-ge-1v4';

UPDATE matches SET kickoff_utc = '2026-06-25T20:00:00Z' WHERE id = 'm-w26-ge-2v3';

UPDATE matches SET kickoff_utc = '2026-06-25T23:00:00Z' WHERE id = 'm-w26-gf-2v3';

UPDATE matches SET kickoff_utc = '2026-06-25T23:00:00Z' WHERE id = 'm-w26-gf-1v4';

UPDATE matches SET kickoff_utc = '2026-06-26T02:00:00Z' WHERE id = 'm-w26-gd-1v4';

UPDATE matches SET kickoff_utc = '2026-06-26T02:00:00Z' WHERE id = 'm-w26-gd-2v3';

UPDATE matches SET kickoff_utc = '2026-06-26T19:00:00Z' WHERE id = 'm-w26-gi-1v4';

UPDATE matches SET kickoff_utc = '2026-06-26T19:00:00Z' WHERE id = 'm-w26-gi-2v3';

UPDATE matches SET kickoff_utc = '2026-06-27T03:00:00Z' WHERE id = 'm-w26-gg-1v4';

UPDATE matches SET kickoff_utc = '2026-06-27T03:00:00Z' WHERE id = 'm-w26-gg-2v3';

UPDATE matches SET kickoff_utc = '2026-06-27T00:00:00Z' WHERE id = 'm-w26-gh-1v4';

UPDATE matches SET kickoff_utc = '2026-06-27T00:00:00Z' WHERE id = 'm-w26-gh-2v3';

UPDATE matches SET kickoff_utc = '2026-06-27T21:00:00Z' WHERE id = 'm-w26-gl-2v3';

UPDATE matches SET kickoff_utc = '2026-06-27T21:00:00Z' WHERE id = 'm-w26-gl-1v4';

UPDATE matches SET kickoff_utc = '2026-06-28T02:00:00Z' WHERE id = 'm-w26-gj-2v3';

UPDATE matches SET kickoff_utc = '2026-06-28T02:00:00Z' WHERE id = 'm-w26-gj-1v4';

UPDATE matches SET kickoff_utc = '2026-06-27T23:30:00Z' WHERE id = 'm-w26-gk-1v4';

UPDATE matches SET kickoff_utc = '2026-06-27T23:30:00Z' WHERE id = 'm-w26-gk-2v3';

UPDATE matches SET kickoff_utc = '2026-06-28T19:00:00Z' WHERE id = 'm-w26-r32-01';

UPDATE matches SET kickoff_utc = '2026-06-29T20:30:00Z' WHERE id = 'm-w26-r32-02';

UPDATE matches SET kickoff_utc = '2026-06-30T01:00:00Z' WHERE id = 'm-w26-r32-03';

UPDATE matches SET kickoff_utc = '2026-06-29T17:00:00Z' WHERE id = 'm-w26-r32-04';

UPDATE matches SET kickoff_utc = '2026-06-30T21:00:00Z' WHERE id = 'm-w26-r32-05';

UPDATE matches SET kickoff_utc = '2026-06-30T17:00:00Z' WHERE id = 'm-w26-r32-06';

UPDATE matches SET kickoff_utc = '2026-07-01T01:00:00Z' WHERE id = 'm-w26-r32-07';

UPDATE matches SET kickoff_utc = '2026-07-01T16:00:00Z' WHERE id = 'm-w26-r32-08';

UPDATE matches SET kickoff_utc = '2026-07-02T00:00:00Z' WHERE id = 'm-w26-r32-09';

UPDATE matches SET kickoff_utc = '2026-07-01T20:00:00Z' WHERE id = 'm-w26-r32-10';

UPDATE matches SET kickoff_utc = '2026-07-02T23:00:00Z' WHERE id = 'm-w26-r32-11';

UPDATE matches SET kickoff_utc = '2026-07-02T19:00:00Z' WHERE id = 'm-w26-r32-12';

UPDATE matches SET kickoff_utc = '2026-07-03T03:00:00Z' WHERE id = 'm-w26-r32-13';

UPDATE matches SET kickoff_utc = '2026-07-03T22:00:00Z' WHERE id = 'm-w26-r32-14';

UPDATE matches SET kickoff_utc = '2026-07-04T01:30:00Z' WHERE id = 'm-w26-r32-15';

UPDATE matches SET kickoff_utc = '2026-07-03T18:00:00Z' WHERE id = 'm-w26-r32-16';

UPDATE matches SET kickoff_utc = '2026-07-04T21:00:00Z' WHERE id = 'm-w26-r16-01';

UPDATE matches SET kickoff_utc = '2026-07-04T17:00:00Z' WHERE id = 'm-w26-r16-02';

UPDATE matches SET kickoff_utc = '2026-07-05T20:00:00Z' WHERE id = 'm-w26-r16-03';

UPDATE matches SET kickoff_utc = '2026-07-06T00:00:00Z' WHERE id = 'm-w26-r16-04';

UPDATE matches SET kickoff_utc = '2026-07-06T19:00:00Z' WHERE id = 'm-w26-r16-05';

UPDATE matches SET kickoff_utc = '2026-07-07T00:00:00Z' WHERE id = 'm-w26-r16-06';

UPDATE matches SET kickoff_utc = '2026-07-07T16:00:00Z' WHERE id = 'm-w26-r16-07';

UPDATE matches SET kickoff_utc = '2026-07-07T20:00:00Z' WHERE id = 'm-w26-r16-08';

UPDATE matches SET kickoff_utc = '2026-07-09T20:00:00Z' WHERE id = 'm-w26-qf-01';

UPDATE matches SET kickoff_utc = '2026-07-10T19:00:00Z' WHERE id = 'm-w26-qf-02';

UPDATE matches SET kickoff_utc = '2026-07-11T21:00:00Z' WHERE id = 'm-w26-qf-03';

UPDATE matches SET kickoff_utc = '2026-07-12T01:00:00Z' WHERE id = 'm-w26-qf-04';

UPDATE matches SET kickoff_utc = '2026-07-14T19:00:00Z' WHERE id = 'm-w26-sf-01';

UPDATE matches SET kickoff_utc = '2026-07-15T19:00:00Z' WHERE id = 'm-w26-sf-02';

UPDATE matches SET kickoff_utc = '2026-07-18T21:00:00Z' WHERE id = 'm-w26-3rd-01';

UPDATE matches SET kickoff_utc = '2026-07-19T19:00:00Z' WHERE id = 'm-w26-final-01';

-- Link all internal matches to FIFA Match Centre ids
UPDATE matches SET fifa_match_id = '400021443', updated_at = datetime('now') WHERE id = 'm-w26-ga-1v2';
UPDATE matches SET fifa_match_id = '400021441', updated_at = datetime('now') WHERE id = 'm-w26-ga-3v4';
UPDATE matches SET fifa_match_id = '400021449', updated_at = datetime('now') WHERE id = 'm-w26-gb-1v2';
UPDATE matches SET fifa_match_id = '400021458', updated_at = datetime('now') WHERE id = 'm-w26-gd-1v2';
UPDATE matches SET fifa_match_id = '400021453', updated_at = datetime('now') WHERE id = 'm-w26-gc-1v2';
UPDATE matches SET fifa_match_id = '400021463', updated_at = datetime('now') WHERE id = 'm-w26-gd-3v4';
UPDATE matches SET fifa_match_id = '400021456', updated_at = datetime('now') WHERE id = 'm-w26-gc-3v4';
UPDATE matches SET fifa_match_id = '400021447', updated_at = datetime('now') WHERE id = 'm-w26-gb-3v4';
UPDATE matches SET fifa_match_id = '400021467', updated_at = datetime('now') WHERE id = 'm-w26-ge-1v2';
UPDATE matches SET fifa_match_id = '400021464', updated_at = datetime('now') WHERE id = 'm-w26-ge-3v4';
UPDATE matches SET fifa_match_id = '400021470', updated_at = datetime('now') WHERE id = 'm-w26-gf-1v2';
UPDATE matches SET fifa_match_id = '400021474', updated_at = datetime('now') WHERE id = 'm-w26-gf-3v4';
UPDATE matches SET fifa_match_id = '400021486', updated_at = datetime('now') WHERE id = 'm-w26-gh-1v2';
UPDATE matches SET fifa_match_id = '400021482', updated_at = datetime('now') WHERE id = 'm-w26-gh-3v4';
UPDATE matches SET fifa_match_id = '400021476', updated_at = datetime('now') WHERE id = 'm-w26-gg-1v2';
UPDATE matches SET fifa_match_id = '400021478', updated_at = datetime('now') WHERE id = 'm-w26-gg-3v4';
UPDATE matches SET fifa_match_id = '400021490', updated_at = datetime('now') WHERE id = 'm-w26-gi-1v2';
UPDATE matches SET fifa_match_id = '400021488', updated_at = datetime('now') WHERE id = 'm-w26-gi-3v4';
UPDATE matches SET fifa_match_id = '400021496', updated_at = datetime('now') WHERE id = 'm-w26-gj-1v2';
UPDATE matches SET fifa_match_id = '400021498', updated_at = datetime('now') WHERE id = 'm-w26-gj-3v4';
UPDATE matches SET fifa_match_id = '400021510', updated_at = datetime('now') WHERE id = 'm-w26-gl-1v2';
UPDATE matches SET fifa_match_id = '400021507', updated_at = datetime('now') WHERE id = 'm-w26-gl-3v4';
UPDATE matches SET fifa_match_id = '400021502', updated_at = datetime('now') WHERE id = 'm-w26-gk-1v2';
UPDATE matches SET fifa_match_id = '400021504', updated_at = datetime('now') WHERE id = 'm-w26-gk-3v4';
UPDATE matches SET fifa_match_id = '400021440', updated_at = datetime('now') WHERE id = 'm-w26-ga-2v4';
UPDATE matches SET fifa_match_id = '400021446', updated_at = datetime('now') WHERE id = 'm-w26-gb-2v4';
UPDATE matches SET fifa_match_id = '400021450', updated_at = datetime('now') WHERE id = 'm-w26-gb-1v3';
UPDATE matches SET fifa_match_id = '400021442', updated_at = datetime('now') WHERE id = 'm-w26-ga-1v3';
UPDATE matches SET fifa_match_id = '400021457', updated_at = datetime('now') WHERE id = 'm-w26-gc-1v3';
UPDATE matches SET fifa_match_id = '400021454', updated_at = datetime('now') WHERE id = 'm-w26-gc-2v4';
UPDATE matches SET fifa_match_id = '400021460', updated_at = datetime('now') WHERE id = 'm-w26-gd-2v4';
UPDATE matches SET fifa_match_id = '400021462', updated_at = datetime('now') WHERE id = 'm-w26-gd-1v3';
UPDATE matches SET fifa_match_id = '400021469', updated_at = datetime('now') WHERE id = 'm-w26-ge-1v3';
UPDATE matches SET fifa_match_id = '400021465', updated_at = datetime('now') WHERE id = 'm-w26-ge-2v4';
UPDATE matches SET fifa_match_id = '400021472', updated_at = datetime('now') WHERE id = 'm-w26-gf-1v3';
UPDATE matches SET fifa_match_id = '400021475', updated_at = datetime('now') WHERE id = 'm-w26-gf-2v4';
UPDATE matches SET fifa_match_id = '400021487', updated_at = datetime('now') WHERE id = 'm-w26-gh-2v4';
UPDATE matches SET fifa_match_id = '400021483', updated_at = datetime('now') WHERE id = 'm-w26-gh-1v3';
UPDATE matches SET fifa_match_id = '400021477', updated_at = datetime('now') WHERE id = 'm-w26-gg-1v3';
UPDATE matches SET fifa_match_id = '400021480', updated_at = datetime('now') WHERE id = 'm-w26-gg-2v4';
UPDATE matches SET fifa_match_id = '400021491', updated_at = datetime('now') WHERE id = 'm-w26-gi-2v4';
UPDATE matches SET fifa_match_id = '400021492', updated_at = datetime('now') WHERE id = 'm-w26-gi-1v3';
UPDATE matches SET fifa_match_id = '400021494', updated_at = datetime('now') WHERE id = 'm-w26-gj-1v3';
UPDATE matches SET fifa_match_id = '400021499', updated_at = datetime('now') WHERE id = 'm-w26-gj-2v4';
UPDATE matches SET fifa_match_id = '400021506', updated_at = datetime('now') WHERE id = 'm-w26-gl-1v3';
UPDATE matches SET fifa_match_id = '400021511', updated_at = datetime('now') WHERE id = 'm-w26-gl-2v4';
UPDATE matches SET fifa_match_id = '400021503', updated_at = datetime('now') WHERE id = 'm-w26-gk-1v3';
UPDATE matches SET fifa_match_id = '400021501', updated_at = datetime('now') WHERE id = 'm-w26-gk-2v4';
UPDATE matches SET fifa_match_id = '400021455', updated_at = datetime('now') WHERE id = 'm-w26-gc-2v3';
UPDATE matches SET fifa_match_id = '400021452', updated_at = datetime('now') WHERE id = 'm-w26-gc-1v4';
UPDATE matches SET fifa_match_id = '400021451', updated_at = datetime('now') WHERE id = 'm-w26-gb-1v4';
UPDATE matches SET fifa_match_id = '400021448', updated_at = datetime('now') WHERE id = 'm-w26-gb-2v3';
UPDATE matches SET fifa_match_id = '400021444', updated_at = datetime('now') WHERE id = 'm-w26-ga-1v4';
UPDATE matches SET fifa_match_id = '400021445', updated_at = datetime('now') WHERE id = 'm-w26-ga-2v3';
UPDATE matches SET fifa_match_id = '400021468', updated_at = datetime('now') WHERE id = 'm-w26-ge-1v4';
UPDATE matches SET fifa_match_id = '400021466', updated_at = datetime('now') WHERE id = 'm-w26-ge-2v3';
UPDATE matches SET fifa_match_id = '400021471', updated_at = datetime('now') WHERE id = 'm-w26-gf-2v3';
UPDATE matches SET fifa_match_id = '400021473', updated_at = datetime('now') WHERE id = 'm-w26-gf-1v4';
UPDATE matches SET fifa_match_id = '400021459', updated_at = datetime('now') WHERE id = 'm-w26-gd-1v4';
UPDATE matches SET fifa_match_id = '400021461', updated_at = datetime('now') WHERE id = 'm-w26-gd-2v3';
UPDATE matches SET fifa_match_id = '400021489', updated_at = datetime('now') WHERE id = 'm-w26-gi-1v4';
UPDATE matches SET fifa_match_id = '400021493', updated_at = datetime('now') WHERE id = 'm-w26-gi-2v3';
UPDATE matches SET fifa_match_id = '400021479', updated_at = datetime('now') WHERE id = 'm-w26-gg-1v4';
UPDATE matches SET fifa_match_id = '400021481', updated_at = datetime('now') WHERE id = 'm-w26-gg-2v3';
UPDATE matches SET fifa_match_id = '400021485', updated_at = datetime('now') WHERE id = 'm-w26-gh-1v4';
UPDATE matches SET fifa_match_id = '400021484', updated_at = datetime('now') WHERE id = 'm-w26-gh-2v3';
UPDATE matches SET fifa_match_id = '400021508', updated_at = datetime('now') WHERE id = 'm-w26-gl-2v3';
UPDATE matches SET fifa_match_id = '400021509', updated_at = datetime('now') WHERE id = 'm-w26-gl-1v4';
UPDATE matches SET fifa_match_id = '400021497', updated_at = datetime('now') WHERE id = 'm-w26-gj-2v3';
UPDATE matches SET fifa_match_id = '400021495', updated_at = datetime('now') WHERE id = 'm-w26-gj-1v4';
UPDATE matches SET fifa_match_id = '400021505', updated_at = datetime('now') WHERE id = 'm-w26-gk-1v4';
UPDATE matches SET fifa_match_id = '400021500', updated_at = datetime('now') WHERE id = 'm-w26-gk-2v3';
UPDATE matches SET fifa_match_id = '400021518', updated_at = datetime('now') WHERE id = 'm-w26-r32-01';
UPDATE matches SET fifa_match_id = '400021513', updated_at = datetime('now') WHERE id = 'm-w26-r32-02';
UPDATE matches SET fifa_match_id = '400021522', updated_at = datetime('now') WHERE id = 'm-w26-r32-03';
UPDATE matches SET fifa_match_id = '400021516', updated_at = datetime('now') WHERE id = 'm-w26-r32-04';
UPDATE matches SET fifa_match_id = '400021523', updated_at = datetime('now') WHERE id = 'm-w26-r32-05';
UPDATE matches SET fifa_match_id = '400021514', updated_at = datetime('now') WHERE id = 'm-w26-r32-06';
UPDATE matches SET fifa_match_id = '400021520', updated_at = datetime('now') WHERE id = 'm-w26-r32-07';
UPDATE matches SET fifa_match_id = '400021512', updated_at = datetime('now') WHERE id = 'm-w26-r32-08';
UPDATE matches SET fifa_match_id = '400021524', updated_at = datetime('now') WHERE id = 'm-w26-r32-09';
UPDATE matches SET fifa_match_id = '400021525', updated_at = datetime('now') WHERE id = 'm-w26-r32-10';
UPDATE matches SET fifa_match_id = '400021526', updated_at = datetime('now') WHERE id = 'm-w26-r32-11';
UPDATE matches SET fifa_match_id = '400021519', updated_at = datetime('now') WHERE id = 'm-w26-r32-12';
UPDATE matches SET fifa_match_id = '400021527', updated_at = datetime('now') WHERE id = 'm-w26-r32-13';
UPDATE matches SET fifa_match_id = '400021521', updated_at = datetime('now') WHERE id = 'm-w26-r32-14';
UPDATE matches SET fifa_match_id = '400021517', updated_at = datetime('now') WHERE id = 'm-w26-r32-15';
UPDATE matches SET fifa_match_id = '400021515', updated_at = datetime('now') WHERE id = 'm-w26-r32-16';
UPDATE matches SET fifa_match_id = '400021533', updated_at = datetime('now') WHERE id = 'm-w26-r16-01';
UPDATE matches SET fifa_match_id = '400021530', updated_at = datetime('now') WHERE id = 'm-w26-r16-02';
UPDATE matches SET fifa_match_id = '400021532', updated_at = datetime('now') WHERE id = 'm-w26-r16-03';
UPDATE matches SET fifa_match_id = '400021531', updated_at = datetime('now') WHERE id = 'm-w26-r16-04';
UPDATE matches SET fifa_match_id = '400021529', updated_at = datetime('now') WHERE id = 'm-w26-r16-05';
UPDATE matches SET fifa_match_id = '400021534', updated_at = datetime('now') WHERE id = 'm-w26-r16-06';
UPDATE matches SET fifa_match_id = '400021528', updated_at = datetime('now') WHERE id = 'm-w26-r16-07';
UPDATE matches SET fifa_match_id = '400021535', updated_at = datetime('now') WHERE id = 'm-w26-r16-08';
UPDATE matches SET fifa_match_id = '400021536', updated_at = datetime('now') WHERE id = 'm-w26-qf-01';
UPDATE matches SET fifa_match_id = '400021538', updated_at = datetime('now') WHERE id = 'm-w26-qf-02';
UPDATE matches SET fifa_match_id = '400021539', updated_at = datetime('now') WHERE id = 'm-w26-qf-03';
UPDATE matches SET fifa_match_id = '400021537', updated_at = datetime('now') WHERE id = 'm-w26-qf-04';
UPDATE matches SET fifa_match_id = '400021541', updated_at = datetime('now') WHERE id = 'm-w26-sf-01';
UPDATE matches SET fifa_match_id = '400021540', updated_at = datetime('now') WHERE id = 'm-w26-sf-02';
UPDATE matches SET fifa_match_id = '400021542', updated_at = datetime('now') WHERE id = 'm-w26-3rd-01';
UPDATE matches SET fifa_match_id = '400021543', updated_at = datetime('now') WHERE id = 'm-w26-final-01';
