-- Fix WC 2026 knockout team pairings from FIFA Match Centre
-- Source: https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/scores-fixtures
-- Generated by scripts/generate-fifa-knockout-fix-migration.mjs on 2026-06-30T02:30:06.527Z
-- Replaces wrong A1-vs-B2 simplified bracket with official FIFA R32 pairings

-- FIFA #73 RSA vs CAN
UPDATE matches SET
  home_team_id = 'team-w26-a2',
  away_team_id = 'team-w26-b1',
  fifa_match_id = '400021518',
  status = 'completed',
  minute = 90,
  home_score = 0,
  away_score = 1,
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-01';

-- FIFA #74 GER vs PAR
UPDATE matches SET
  home_team_id = 'team-w26-e3',
  away_team_id = 'team-w26-d2',
  fifa_match_id = '400021513',
  status = 'completed',
  minute = 90,
  home_score = 1,
  away_score = 1,
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-02';

-- FIFA #75 NED vs MAR
UPDATE matches SET
  home_team_id = 'team-w26-f1',
  away_team_id = 'team-w26-c4',
  fifa_match_id = '400021522',
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-03';

-- FIFA #76 BRA vs JPN
UPDATE matches SET
  home_team_id = 'team-w26-c3',
  away_team_id = 'team-w26-f2',
  fifa_match_id = '400021516',
  status = 'completed',
  minute = 90,
  home_score = 2,
  away_score = 1,
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-04';

-- FIFA #77 FRA vs SWE
UPDATE matches SET
  home_team_id = 'team-w26-i1',
  away_team_id = 'team-w26-f3',
  fifa_match_id = '400021523',
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-05';

-- FIFA #78 CIV vs NOR
UPDATE matches SET
  home_team_id = 'team-w26-e1',
  away_team_id = 'team-w26-i4',
  fifa_match_id = '400021514',
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-06';

-- FIFA #79 MEX vs ECU
UPDATE matches SET
  home_team_id = 'team-w26-a1',
  away_team_id = 'team-w26-e2',
  fifa_match_id = '400021520',
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-07';

-- FIFA #80 ENG vs COD
UPDATE matches SET
  home_team_id = 'team-w26-l3',
  away_team_id = 'team-w26-k2',
  fifa_match_id = '400021512',
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-08';

-- FIFA #81 USA vs BIH
UPDATE matches SET
  home_team_id = 'team-w26-d1',
  away_team_id = 'team-w26-b2',
  fifa_match_id = '400021524',
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-09';

-- FIFA #82 BEL vs SEN
UPDATE matches SET
  home_team_id = 'team-w26-g3',
  away_team_id = 'team-w26-i2',
  fifa_match_id = '400021525',
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-10';

-- FIFA #83 POR vs CRO
UPDATE matches SET
  home_team_id = 'team-w26-k1',
  away_team_id = 'team-w26-l4',
  fifa_match_id = '400021526',
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-11';

-- FIFA #84 ESP vs AUT
UPDATE matches SET
  home_team_id = 'team-w26-h3',
  away_team_id = 'team-w26-j3',
  fifa_match_id = '400021519',
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-12';

-- FIFA #85 SUI vs ALG
UPDATE matches SET
  home_team_id = 'team-w26-b4',
  away_team_id = 'team-w26-j2',
  fifa_match_id = '400021527',
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-13';

-- FIFA #86 ARG vs CPV
UPDATE matches SET
  home_team_id = 'team-w26-j1',
  away_team_id = 'team-w26-h4',
  fifa_match_id = '400021521',
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-14';

-- FIFA #87 COL vs GHA
UPDATE matches SET
  home_team_id = 'team-w26-k4',
  away_team_id = 'team-w26-l1',
  fifa_match_id = '400021517',
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-15';

-- FIFA #88 AUS vs EGY
UPDATE matches SET
  home_team_id = 'team-w26-d3',
  away_team_id = 'team-w26-g4',
  fifa_match_id = '400021515',
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-16';
