-- Replace simplified R32 group_rank bracket links with FIFA official pairings
-- Third-place slots (1X vs 3Y) are filled by applyBestThirdQualifiers, not bracket links
-- Generated by scripts/generate-fifa-knockout-fix-migration.mjs on 2026-06-30T02:30:06.528Z

DELETE FROM match_bracket_links
WHERE tournament_id = 't-2026'
  AND rule_type = 'group_rank'
  AND target_match_id LIKE 'm-w26-r32-%';

INSERT INTO match_bracket_links (id, tournament_id, source_match_id, target_match_id, target_slot, rule_type, rule_json) VALUES
  ('bl-fifa-r32-01-h', 't-2026', NULL, 'm-w26-r32-01', 'home', 'group_rank', '{"group":"A","rank":2}'),
  ('bl-fifa-r32-01-a', 't-2026', NULL, 'm-w26-r32-01', 'away', 'group_rank', '{"group":"B","rank":2}'),
  ('bl-fifa-r32-02-h', 't-2026', NULL, 'm-w26-r32-02', 'home', 'group_rank', '{"group":"E","rank":1}'),
  ('bl-fifa-r32-03-h', 't-2026', NULL, 'm-w26-r32-03', 'home', 'group_rank', '{"group":"F","rank":1}'),
  ('bl-fifa-r32-03-a', 't-2026', NULL, 'm-w26-r32-03', 'away', 'group_rank', '{"group":"C","rank":2}'),
  ('bl-fifa-r32-04-h', 't-2026', NULL, 'm-w26-r32-04', 'home', 'group_rank', '{"group":"C","rank":1}'),
  ('bl-fifa-r32-04-a', 't-2026', NULL, 'm-w26-r32-04', 'away', 'group_rank', '{"group":"F","rank":2}'),
  ('bl-fifa-r32-05-h', 't-2026', NULL, 'm-w26-r32-05', 'home', 'group_rank', '{"group":"I","rank":1}'),
  ('bl-fifa-r32-06-h', 't-2026', NULL, 'm-w26-r32-06', 'home', 'group_rank', '{"group":"E","rank":2}'),
  ('bl-fifa-r32-06-a', 't-2026', NULL, 'm-w26-r32-06', 'away', 'group_rank', '{"group":"I","rank":2}'),
  ('bl-fifa-r32-07-h', 't-2026', NULL, 'm-w26-r32-07', 'home', 'group_rank', '{"group":"A","rank":1}'),
  ('bl-fifa-r32-08-h', 't-2026', NULL, 'm-w26-r32-08', 'home', 'group_rank', '{"group":"L","rank":1}'),
  ('bl-fifa-r32-09-h', 't-2026', NULL, 'm-w26-r32-09', 'home', 'group_rank', '{"group":"D","rank":1}'),
  ('bl-fifa-r32-10-h', 't-2026', NULL, 'm-w26-r32-10', 'home', 'group_rank', '{"group":"G","rank":1}'),
  ('bl-fifa-r32-11-h', 't-2026', NULL, 'm-w26-r32-11', 'home', 'group_rank', '{"group":"K","rank":2}'),
  ('bl-fifa-r32-11-a', 't-2026', NULL, 'm-w26-r32-11', 'away', 'group_rank', '{"group":"L","rank":2}'),
  ('bl-fifa-r32-12-h', 't-2026', NULL, 'm-w26-r32-12', 'home', 'group_rank', '{"group":"H","rank":1}'),
  ('bl-fifa-r32-12-a', 't-2026', NULL, 'm-w26-r32-12', 'away', 'group_rank', '{"group":"J","rank":2}'),
  ('bl-fifa-r32-13-h', 't-2026', NULL, 'm-w26-r32-13', 'home', 'group_rank', '{"group":"B","rank":1}'),
  ('bl-fifa-r32-14-h', 't-2026', NULL, 'm-w26-r32-14', 'home', 'group_rank', '{"group":"J","rank":1}'),
  ('bl-fifa-r32-14-a', 't-2026', NULL, 'm-w26-r32-14', 'away', 'group_rank', '{"group":"H","rank":2}'),
  ('bl-fifa-r32-15-h', 't-2026', NULL, 'm-w26-r32-15', 'home', 'group_rank', '{"group":"K","rank":1}'),
  ('bl-fifa-r32-16-h', 't-2026', NULL, 'm-w26-r32-16', 'home', 'group_rank', '{"group":"D","rank":2}'),
  ('bl-fifa-r32-16-a', 't-2026', NULL, 'm-w26-r32-16', 'away', 'group_rank', '{"group":"G","rank":2}');
