-- Round of 16 teams from FIFA Match Centre (+ repair R32 13–16)
-- Source: https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/scores-fixtures
-- Generated by scripts/generate-fifa-r16-migration.mjs on 2026-07-05T23:57:31.288Z

-- FIFA #85 SUI vs ALG
UPDATE matches SET
  home_team_id = 'team-w26-b4',
  away_team_id = 'team-w26-j2',
  fifa_match_id = '400021527',
  status = 'completed',
  minute = 90,
  home_score = 2,
  away_score = 0,
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-13';

-- FIFA #86 ARG vs CPV
UPDATE matches SET
  home_team_id = 'team-w26-j1',
  away_team_id = 'team-w26-h4',
  fifa_match_id = '400021521',
  status = 'completed',
  minute = 90,
  home_score = 3,
  away_score = 2,
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-14';

-- FIFA #87 COL vs GHA
UPDATE matches SET
  home_team_id = 'team-w26-k4',
  away_team_id = 'team-w26-l1',
  fifa_match_id = '400021517',
  status = 'completed',
  minute = 90,
  home_score = 1,
  away_score = 0,
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-15';

-- FIFA #88 AUS vs EGY
UPDATE matches SET
  home_team_id = 'team-w26-d3',
  away_team_id = 'team-w26-g4',
  fifa_match_id = '400021515',
  status = 'completed',
  minute = 90,
  home_score = 1,
  away_score = 1,
  updated_at = datetime('now')
WHERE id = 'm-w26-r32-16';

-- FIFA #89 PAR vs FRA
UPDATE matches SET
  home_team_id = 'team-w26-d2',
  away_team_id = 'team-w26-i1',
  fifa_match_id = '400021533',
  status = 'completed',
  minute = 90,
  home_score = 0,
  away_score = 1,
  updated_at = datetime('now')
WHERE id = 'm-w26-r16-01';

-- FIFA #90 CAN vs MAR
UPDATE matches SET
  home_team_id = 'team-w26-b1',
  away_team_id = 'team-w26-c4',
  fifa_match_id = '400021530',
  status = 'completed',
  minute = 90,
  home_score = 0,
  away_score = 3,
  updated_at = datetime('now')
WHERE id = 'm-w26-r16-02';

-- FIFA #91 BRA vs NOR
UPDATE matches SET
  home_team_id = 'team-w26-c3',
  away_team_id = 'team-w26-i4',
  fifa_match_id = '400021532',
  status = 'completed',
  minute = 90,
  home_score = 1,
  away_score = 2,
  updated_at = datetime('now')
WHERE id = 'm-w26-r16-03';

-- FIFA #92 MEX vs ENG
UPDATE matches SET
  home_team_id = 'team-w26-a1',
  away_team_id = 'team-w26-l3',
  fifa_match_id = '400021531',
  status = 'scheduled',
  minute = 0,
  home_score = 0,
  away_score = 0,
  updated_at = datetime('now')
WHERE id = 'm-w26-r16-04';

-- FIFA #93 POR vs ESP
UPDATE matches SET
  home_team_id = 'team-w26-k1',
  away_team_id = 'team-w26-h3',
  fifa_match_id = '400021529',
  status = 'scheduled',
  minute = 0,
  home_score = 0,
  away_score = 0,
  updated_at = datetime('now')
WHERE id = 'm-w26-r16-05';

-- FIFA #94 USA vs BEL
UPDATE matches SET
  home_team_id = 'team-w26-d1',
  away_team_id = 'team-w26-g3',
  fifa_match_id = '400021534',
  status = 'scheduled',
  minute = 0,
  home_score = 0,
  away_score = 0,
  updated_at = datetime('now')
WHERE id = 'm-w26-r16-06';

-- FIFA #95 ARG vs EGY
UPDATE matches SET
  home_team_id = 'team-w26-j1',
  away_team_id = 'team-w26-g4',
  fifa_match_id = '400021528',
  status = 'scheduled',
  minute = 0,
  home_score = 0,
  away_score = 0,
  updated_at = datetime('now')
WHERE id = 'm-w26-r16-07';

-- FIFA #96 SUI vs COL
UPDATE matches SET
  home_team_id = 'team-w26-b4',
  away_team_id = 'team-w26-k4',
  fifa_match_id = '400021535',
  status = 'scheduled',
  minute = 0,
  home_score = 0,
  away_score = 0,
  updated_at = datetime('now')
WHERE id = 'm-w26-r16-08';
