import { createRef } from 'react';
import type { ScenarioItem } from '../../app/lib/api';
import { API_DOC_SECTIONS } from '../../app/lib/apiDocsContent';

const sampleEndpoint =
  API_DOC_SECTIONS.find((s) => s.endpoints?.length)?.endpoints?.[0] ?? {
    method: 'GET' as const,
    path: '/api/health',
    title: 'Health',
    description: 'Health check',
  };

const sampleScenario: ScenarioItem = {
  scenarioType: 'upset',
  probability: 0.2,
  confidence: 0.7,
  explanationFactors: ['form'],
};

const sampleLineupSide = {
  teamName: 'USA',
  formation: '4-3-3',
  hasAccurateLineup: false,
  hasLineup: false,
  source: 'projected',
  starters: [],
  substitutes: [],
  grouped: { GK: [], DEF: [], MID: [], FWD: [] },
  lineupPlayers: [],
  players: [],
};

const sampleArticle = {
  id: 'n-test',
  title: 'Test article',
  source_url: 'https://example.com',
  summary: 'Summary',
  published_at: '2026-01-01T00:00:00Z',
  reliability_score: 0.8,
};

const sampleMatch = {
  id: 'm-test',
  home_team_id: 't-usa',
  away_team_id: 't-mex',
  home_name: 'USA',
  away_name: 'Mexico',
  status: 'scheduled',
  home_score: 0,
  away_score: 0,
  kickoff_utc: '2026-06-11T20:00:00Z',
};

/** Default props for component smoke renders keyed by export name. */
export const COMPONENT_PROPS: Record<string, Record<string, unknown>> = {
  AnalystSimulatorPanel: {
    base: { homeWin: 0.4, draw: 0.3, awayWin: 0.3, xgHome: 1.2, xgAway: 1.0 },
  },
  BracketPanel: {},
  BrandLogo: {},
  Bilingual: { k: 'common.loading' },
  BilingualText: { k: 'common.loading' },
  BiHint: { vi: 'Xin chào', en: 'Hello' },
  CodeBlock: { code: 'curl /api/health' },
  CompactMatchProb: { homeWin: 0.4, draw: 0.3, awayWin: 0.3 },
  ContributionRadialChart: { segments: [], title: 'Impact' },
  DataKindBadge: { kind: 'predicted' },
  DataKindMark: { kind: 'actual' },
  DataKindLegend: {},
  EditorialArticleLayout: { title: 'Test', children: 'Body' },
  EndpointCard: {
    endpoint: sampleEndpoint,
    origin: 'https://example.com',
  },
  EventTrajectoryLayer: { events: [] },
  FavoriteButton: { active: false, onToggle: () => {}, label: 'Favorite' },
  FeaturedMatchHero: { match: sampleMatch },
  FavoritesPanel: { matches: [], teams: [] },
  GroupStageBoard: { matches: [] },
  GroupStandingsGrid: {},
  HomeNewsPreview: {},
  HomePageSkeleton: {},
  LangSwitch: {},
  LineupColumn: { side: sampleLineupSide, label: 'Home' },
  MarketDisclaimer: {},
  MarketSignalPanel: {
    payload: {
      signals: {
        matchId: 'm-test',
        model: { home: 0.4, draw: 0.3, away: 0.3 },
        market: { home: 0.38, draw: 0.28, away: 0.34 },
        edge: { home: 0.02, draw: 0.02, away: -0.04 },
        volatilityScore: 0.1,
        updatedAt: '2026-01-01T00:00:00Z',
        disclaimer: 'Test',
      },
      oddsSnapshots: [],
      disclaimer: 'Test',
    },
    loading: false,
  },
  MatchAnalyticsPanel: { matchId: 'm-test', homeWin: 0.4, awayWin: 0.3 },
  MatchHeader: {
    home: 'USA',
    away: 'Mexico',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
  },
  MatchHistoryPanel: {
    homeName: 'USA',
    awayName: 'Mexico',
    history: [],
    summary: { meetings: 0, homeWins: 0, awayWins: 0, draws: 0 },
  },
  MatchKickoffCountdown: { kickoffUtc: '2026-06-30T00:00:00Z', status: 'scheduled' },
  MatchKickoffDisplay: { kickoffUtc: '2026-06-30T00:00:00Z', status: 'scheduled' },
  MatchLineupSidePanel: { side: sampleLineupSide, label: 'Home' },
  MatchLiveStatsPanel: { matchId: 'm-test', homeLabel: 'USA', awayLabel: 'Mexico' },
  MatchPageGuideStrip: {},
  MatchPredictionSummary: {
    homeWin: 0.4,
    draw: 0.3,
    awayWin: 0.3,
    homeLabel: 'USA',
    awayLabel: 'Mexico',
  },
  MatchPreviewAnalysisPanel: { preview: null, loading: true },
  MatchRecapPanel: { matchId: 'm-test', homeLabel: 'USA', awayLabel: 'Mexico' },
  MatchResultScore: { homeScore: 1, awayScore: 0, status: 'completed' },
  MatchScheduleCalendar: { byDate: {}, matches: [] },
  MatchSectionNav: {
    active: 'overview',
    onSelect: () => {},
    sectionRefs: {
      overview: createRef<HTMLElement>(),
      stats: createRef<HTMLElement>(),
      prediction: createRef<HTMLElement>(),
      momentum: createRef<HTMLElement>(),
      tactical: createRef<HTMLElement>(),
      scenarios: createRef<HTMLElement>(),
    },
  },
  MatchStaffPanel: { matchId: 'm-test', homeLabel: 'USA', awayLabel: 'Mexico' },
  MatchStickyScoreBar: {
    home: 'USA',
    away: 'Mexico',
    homeScore: 0,
    awayScore: 0,
    status: 'scheduled',
    visible: true,
  },
  MatchVersusThumbnail: { homeName: 'USA', awayName: 'Mexico', homeCountryCode: 'US', awayCountryCode: 'MX' },
  MethodBadge: { method: 'GET' },
  ModelVsMarketChart: {
    data: {
      matchId: 'm-test',
      model: { home: 0.4, draw: 0.3, away: 0.3 },
      market: { home: 0.38, draw: 0.28, away: 0.34 },
      edge: { home: 0.02, draw: 0.02, away: -0.04 },
      volatilityScore: 0.1,
      updatedAt: '2026-01-01T00:00:00Z',
      disclaimer: 'Test',
    },
  },
  MultiVariablePanel: { analysis: null, loading: true },
  NewUserQuickStart: {},
  NewsArticleCard: { article: sampleArticle, onSelect: () => {} },
  NewsArticleLangToggle: { lang: 'vi', onChange: () => {} },
  NewsArticleReadView: {
    article: sampleArticle,
    articleLang: 'vi',
    onArticleLangChange: () => {},
    onBack: () => {},
  },
  NewsFeedPanel: {
    hot: [],
    articles: [],
    lastCrawl: null,
    page: 1,
    totalPages: 1,
    onPageChange: () => {},
    onSelectArticle: () => {},
  },
  NewsPagination: { page: 1, totalPages: 3, onPageChange: () => {} },
  NewsThumbnail: { article: sampleArticle },
  PitchMap: { data: null, loading: false },
  PitchPlayerLayer: { players: [], side: 'home' },
  PlatformSnapshot: {
    dashboard: {
      featuredMatch: null,
      matchCount: 0,
      lastDataRefresh: null,
      lastNewsCrawl: null,
      refreshIntervalSec: 30,
      newsCrawlIntervalSec: 900,
      expectedMatches: 104,
      hostCountries: ['USA', 'Mexico', 'Canada'],
      teamsCount: 48,
      groupCount: 12,
      statusCounts: { scheduled: 104, live: 0, completed: 0 },
    },
  },
  PlayerImpactCard: {
    players: [
      { id: 'p1', name: 'Player One', role: 'FW', team: 'home', impact: 0.8, xg: 0.5 },
    ],
  },
  ProbabilityHintsPanel: {
    hints: [{ id: 'h1', vi: 'Gợi ý', en: 'Hint', type: 'form' }],
  },
  ProbabilityMovementTimeline: {
    intervals: {
      '15': { homeWinProb: 0.4, drawProb: 0.3, awayWinProb: 0.3 },
      '45': { homeWinProb: 0.42, drawProb: 0.28, awayWinProb: 0.3 },
    },
  },
  PredictedActualScores: { homeScore: 1, awayScore: 0, status: 'completed' },
  ProbabilityDeltaBadge: { delta: 0.05 },
  ProbabilityMovementPanel: { matchId: 'm-test', prob: null },
  ProbabilityStrip: { homeWin: 0.4, draw: 0.3, awayWin: 0.3 },
  ScenarioCard: { scenario: sampleScenario },
  ScenarioComparisonCard: {
    data: {
      matchId: 'm-test',
      generatedAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
      scenarios: [],
      comparison: {
        primaryScenarioId: 's1',
        alternativeScenarioId: 's2',
        probabilityGap: 0.1,
        confidenceGap: 0.05,
        summary: 'Comparison summary',
        keyDifferences: ['Difference one'],
        homeWinDelta: 0.02,
        drawDelta: -0.01,
        awayWinDelta: -0.01,
        xgHomeDelta: 0.1,
        xgAwayDelta: -0.05,
      },
      sourceConfidence: { overall: 0.8, notes: [] },
    },
  },
  SourceConfidencePanel: { sources: [{ name: 'FIFA', score: 0.9 }] },
  ScenarioConditionList: {
    title: 'Conditions',
    items: [{ condition: 'score', value: '1-0', confidence: 0.8 }],
  },
  ScenarioConfidenceBadge: { value: 0.8 },
  ScenarioConfidenceInline: {
    scenario: {
      id: 's1',
      matchId: 'm-test',
      scenarioType: 'baseline',
      scenarioName: 'Baseline',
      scenarioRank: 1,
      isBaseline: true,
      initialConditions: [],
      triggerConditions: [],
      invalidationConditions: [],
      scenarioProbability: 0.5,
      scenarioConfidence: 0.8,
      homeWinProb: 0.4,
      drawProb: 0.3,
      awayWinProb: 0.3,
      mostLikelyScoreline: '1-1',
      updatedAt: '2026-01-01T00:00:00Z',
    },
  },
  ScenarioLikelihoodPanel: { data: null, loading: true },
  ScenarioPredictionPanel: { data: null, loading: true },
  ScenarioProbabilityBar: { label: 'Likelihood', value: 0.5 },
  ScenarioRealtimeTimeline: { updatedAt: '2026-01-01T00:00:00Z' },
  ScorelineMatrix: { distribution: { '1-0': 0.15, '1-1': 0.12 } },
  ScenarioTriggerStatus: {
    scenario: {
      id: 's1',
      matchId: 'm-test',
      scenarioType: 'baseline',
      scenarioName: 'Baseline',
      scenarioRank: 1,
      isBaseline: true,
      initialConditions: [],
      triggerConditions: [],
      invalidationConditions: [],
      scenarioProbability: 0.5,
      scenarioConfidence: 0.8,
      homeWinProb: 0.4,
      drawProb: 0.3,
      awayWinProb: 0.3,
      mostLikelyScoreline: '1-1',
      updatedAt: '2026-01-01T00:00:00Z',
    },
  },
  ScheduleTimezoneBanner: {},
  SectionLabel: { title: 'Section' },
  SourceConfidenceBadge: { name: 'FIFA', score: 0.9 },
  TacticalBriefingPanel: { briefing: null, loading: true },
  TeamNameWithFlag: { name: 'USA', countryCode: 'US' },
  MatchTeamsWithFlags: {
    home: { name: 'USA', countryCode: 'US' },
    away: { name: 'Mexico', countryCode: 'MX' },
  },
  TeamSystemPanel: { home: null, away: null, loading: true },
  TeamsDirectory: { teams: [] },
  TeamWorldCupH2HPanel: { teamName: 'USA', opponents: [], totalMeetings: 0 },
  TournamentSchedulePanel: { byDate: {}, matches: [] },
  ViewModeToggle: { mode: 'tactical', onChange: () => {} },
  WorldCupCountdown: { targetUtc: '2026-06-11T14:00:00Z', title: 'WC 2026' },
};

/** Components that need nested Routes (Outlet or route hooks). */
export const ROUTE_WRAPPED_COMPONENTS = new Set(['AppShell']);
